### PR TITLE
PR Work/valentin/final approach.real tests

### PR DESCRIPTION
**Pull request by ValentinVERGEZ**
NE PAS SUPPRIMER LA BRANCHE

Beaucoup de petits ajouts pour répondre aux diverses problèmes rencontrés sur les tests de l'approche finale en réel.

---

This change is [Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/83)

### CODE REVIEW

**Comment by vcoelen** [comment]
Reviewed 28 of 32 files at r1.
Review status: 26 of 30 files reviewed at latest revision, 14 unresolved discussions.

---

_[common/common_utils/src/RateLimiter.cpp, line 20 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFj8PJYldeVq_TM_-e:-KLFj8PKIuguo3qqrZF0:-1894995094) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/common/common_utils/src/RateLimiter.cpp#L20)):_

> ``` cpp
> RateLimiter::RateLimiter(float low, float up, float T)
> {
>     void setLimits(float low, float up);
> ```

voir mise à jour dans navigation_devel

---

_[common/common_utils/src/controller/PidWithAntiWindUp.cpp, line 64 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFjc8fn60XuBvyinJ6:-KLFjc8gOUrdeWyXIFr7:492842675) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/common/common_utils/src/controller/PidWithAntiWindUp.cpp#L64)):_

> ``` cpp
>     else if (pidOutTemp <= m_lowLim)
>     {
>         pidOut = m_highLim;
> ```

m_lowLim

---

_[navigation/final_approach/include/final_approach/FinalApproaching.h, line 400 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFkQwLXKqxhwYjh-Nx:-KLFkQwLXKqxhwYjh-Ny:793076092) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/include/final_approach/FinalApproaching.h#L400)):_

> ``` objc
>    *
>    * \param[in]  allPossibleId  The all possible identifier
>    * \param[in]  arTags         The artags vector
> ```

Mix anglais/français

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 251 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFlhNiR9az3hBetgth:-KLFlhNiR9az3hBetgti:-536611219) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L251)):_

> ``` cpp
>   if (m_skipAsservCamera())
>   {
>       avancementArTag = 1;
> ```

Pourquoi "1"?

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 266 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFlz55ZfnGg1yBt-W0:-KLFlz55ZfnGg1yBt-W1:1784590400) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L266)):_

> ``` cpp
>   ROS_INFO("LaserScan Asservissement");
>   firstTimeInLoop = true;
>   while (ros::ok() && !bp.getState() && locateArTagPhase != 3 && avancementArTag == 1 && !laserAsservDone && obstacle == false
> ```

!laserAsservDone && obstacle == false deux manières de faire la même chose

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 327 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFmK0vPab8m-PuQU0N:-KLFmK0vPab8m-PuQU0O:1804666432) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L327)):_

> ``` cpp
>       // pourra s'avérer utile. A voir.
>       angleAsservDone = asservissementAngle(M_PI/2, seg.getAngle());
>       asservLaserYawOk_cpt = angleAsservDone ? ++asservLaserYawOk_cpt : 0;
> ```

"asservLaserYawOk_cpt+1" serait plus logique/joli que "++asservLaserYawOk_cpt" même si ça fait la même chose

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 350 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFmlFEnnNV3pXJuogB:-KLFmlFEnnNV3pXJuogC:677726600) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L350)):_

> ``` cpp
>           ROS_WARN("X - OBJ: %f, MEAS: %f", objectifX(), -seg.distanceOrthoLaserSegment());
>           xAsservDone = asservissementPositionX(objectifX(), -seg.distanceOrthoLaserSegment());
>           asservLaserXOk_cpt = xAsservDone ? ++asservLaserXOk_cpt : 0;
> ```

idem

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 388 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFn16yQonOV47S_cvp:-KLFn16yQonOV47S_cvq:651973074) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L388)):_

> ``` cpp
>   // TODO: Utiliser les plotData
>   // TODO: Faire un bon feedback
>   m_feedback.percent_complete = 100;
> ```

On passe de 40 à 100% très vite ;)

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 557 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFnKp1igadkUZgd4xw:-KLFnKp1igadkUZgd4xx:-851300751) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L557)):_

> ``` cpp
>                                                             std::vector<float> ranges, float angleMin, double angleInc)
> {
>   constexpr float mpsWidthRelativeMargin = 0.10;
> ```

un "const" suffira je pense

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 930 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFnnGeLcKh1ZnRm_2e:-KLFnnGeLcKh1ZnRm_2f:-589743560) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L930)):_

> ``` cpp
>           {
>               ROS_DEBUG_NAMED("investigation", "Possible %d VS Found %d", allPossibleId[i], arTags[k].id);
>               if (allPossibleId[k] == arTags[k].id)
> ```

Pourquoi pas "i" à la place de "k" dans "allPossibleId[k]"

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 1001 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFnZVMN3ChZYuo3RFG:-KLFnZVMN3ChZYuo3RFH:-470516354) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L1001)):_

> ``` cpp
> bool FinalApproaching::asservissementCameraNew(const arTag_t &target)
> {
>   constexpr int jarResetValue = 3;
> ```

const

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 1010 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFoFo_smpCFhOXwGvm:-KLFoFo_smpCFhOXwGvn:-1103789407) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L1010)):_

> ``` cpp
>   static int yawSuccessJar = jarResetValue;
> 
>   float errX = target.pose.position.z - 0.50;  // A corriger une fois les transformations appliquée
> ```

magic number

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 1023 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFoNfB9vW7xW4sTOMA:-KLFoNfB9vW7xW4sTOMB:-1103789407) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L1023)):_

> ``` cpp
>   {
>       // Asserv en Y
>       if (std::abs(errY) < 0.005) // 0.5cm
> ```

magic number

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 1033 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFoQ88jLPaZGUQdiX5:-KLFoQ89yucrWuLuvm2U:677726600) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L1033)):_

> ``` cpp
>       else
>       {
>           m_msgTwist.linear.y = 0.75 * errY;
> ```

idem

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83)_

**Comment by ValentinVERGEZ** [comment]
Review status: 26 of 30 files reviewed at latest revision, 14 unresolved discussions.

---

_[common/common_utils/src/RateLimiter.cpp, line 20 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFj8PJYldeVq_TM_-e:-KLG3oeaWkvF33oh0x9u:222820958) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/common/common_utils/src/RateLimiter.cpp#L20)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> voir mise à jour dans navigation_devel
> </details>
> Je touche pas, le code de navigation-devel sera remergé.

---

_[common/common_utils/src/controller/PidWithAntiWindUp.cpp, line 64 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFjc8fn60XuBvyinJ6:-KLG6nABlwRCArLoFUF8:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/common/common_utils/src/controller/PidWithAntiWindUp.cpp#L64)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> m_lowLim
> </details>
> Done.

---

_[navigation/final_approach/include/final_approach/FinalApproaching.h, line 400 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFkQwLXKqxhwYjh-Nx:-KLG4S43p69zbnRcWKG8:86041746) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/include/final_approach/FinalApproaching.h#L400)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> Mix anglais/français
> </details>
> C'est vraiment gênant ? C'est mon plugin Doxygen qui fait lui-même la doc, quand elle est correcte je la laisse.

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 251 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFlhNiR9az3hBetgth:-KLG0sbhS8TAEJCmb-lu:745537952) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L251)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> Pourquoi "1"?
> </details>
> Code Cyril, pas trouvé de nom de const pertinent

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 266 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFlz55ZfnGg1yBt-W0:-KLG5_qaR3w2--cZJg56:-555125326) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L266)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> !laserAsservDone && obstacle == false deux manières de faire la même chose
> </details>
> Oui plus ou moins. Je ne le change pas ici.

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 327 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFmK0vPab8m-PuQU0N:-KLG6lE_QjOdU9ls5E3m:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L327)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> "asservLaserYawOk_cpt+1" serait plus logique/joli que "++asservLaserYawOk_cpt" même si ça fait la même chose
> </details>
> Done.

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 350 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFmlFEnnNV3pXJuogB:-KLG6qsNi-ragPOoLGnw:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L350)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> idem
> </details>
> Done.

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 388 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFn16yQonOV47S_cvp:-KLGKsVLRFQAokPIfXeu:331641807) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L388)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> On passe de 40 à 100% très vite ;)
> </details>
> :-D oui

C'est déjà mieux que rien non ? J'ai plus ou moins une idée de la phase de l'approche dans le feedback.
Mais oui, oui ça doit être amélioré.

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 557 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFnKp1igadkUZgd4xw:-KLGq5ezFkIQglE8f4_e:-1060728038) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L557)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> un "const" suffira je pense
> </details>
> Suite à la discussion et à ma compréhension des constexpr (très certainement incomplète je veux bien l'admettre), je garderai les flottants, même des simples constantes, en constexpr.
> En revanche les entiers, c'est overkill.

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 930 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFnnGeLcKh1ZnRm_2e:-KLGrXwQz75Z0zfn7HtD:-1176201954) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L930)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> Pourquoi pas "i" à la place de "k" dans "allPossibleId[k]"
> </details>
> ... franchement, j'en sais rien.

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 1001 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFnZVMN3ChZYuo3RFG:-KLGtLJv34AXJBD0X4mD:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L1001)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> const
> </details>
> Done.

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 1010 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFoFo_smpCFhOXwGvm:-KLGtM0GqLhbk59s1o5A:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L1010)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> magic number
> </details>
> Done.

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 1023 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFoNfB9vW7xW4sTOMA:-KLGtGfT0GpwaBxkMJFl:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L1023)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> magic number
> </details>
> Done.

---

_[navigation/final_approach/src/FinalApproaching.cpp, line 1033 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-KLFoQ88jLPaZGUQdiX5:-KLGtHb6VPKjza_KIJ9X:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/428b18ea1343d96632ac2e80aa2a9adeccb1f422/navigation/final_approach/src/FinalApproaching.cpp#L1033)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> idem
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83)_

**Comment by vcoelen** [comment]
Reviewed 4 of 32 files at r1.
Review status: 25 of 30 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83)_

**Comment by vcoelen** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83)_

**Comment by vcoelen** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/83#-:-KLH-3bHzNIE9mwfSnAK:1417088721)_

**Pull request merged**
