### PR TITLE
Work/valentin/simulator/port bob

### PR DESCRIPTION
**Pull request by ValentinVERGEZ**
De multiples corrections ont été apportées sur BOB. Il y a aussi eu plusieurs ajouts pour pouvoir utiliser le simulateur avec six robots.

C'est un port de ces modifications sur STUART.

N'hésitez pas à poser des questions. J'ai bien conscience que j'ouvre cette pull-request un peu trop à l'arrache.

[Review on Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/38)

### CODE REVIEW

**Comment by vianneyPayelle** [comment]
Reviewed 1 of 28 files at r1.
Review status: 1 of 28 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[navigation/localisation/src/Cartographie.cpp, line 42 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K892fbUfsiX4jSHGlEi:-K892fbUfsiX4jSHGlEj:892333233) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/0f151e800aa9217b49fa2381851fc2e63ed12281/navigation/localisation/src/Cartographie.cpp#L42)):_
Attention printf à remplacer par ROS_INFO

---

_[navigation/localisation/src/Cartographie.cpp, line 61 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K8937Nr3UnVrKME-kIy:-K8937Ns8qTMUZRAaP0K:892333233) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/0f151e800aa9217b49fa2381851fc2e63ed12281/navigation/localisation/src/Cartographie.cpp#L61)):_
Attention printf à remplacer par ROS_INFO

---

_[navigation/localisation/src/Cartographie.cpp, line 75 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K8939yVSP4DbUheSwn-:-K8939yW0dyHh5vCk818:892333233) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/0f151e800aa9217b49fa2381851fc2e63ed12281/navigation/localisation/src/Cartographie.cpp#L75)):_
Attention printf à remplacer par ROS_INFO

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38)_

**Comment by vianneyPayelle** [comment]
Broken build à réparer

**Comment by vcoelen** [comment]
Reviewed 27 of 28 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

_[navigation/localisation/src/Cartographie.cpp, line 40 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89ai5MtdOOm35IRe3Z:-K89ai5Ncl4QftHXJI6I:-1669944668) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/0f151e800aa9217b49fa2381851fc2e63ed12281/navigation/localisation/src/Cartographie.cpp#L40)):_
Non respect des règles de codages

---

_[navigation/localisation/src/Cartographie.cpp, line 104 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89asMlmRo-kFsrJ0Ve:-K89asMlmRo-kFsrJ0Vf:-1669944668) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/0f151e800aa9217b49fa2381851fc2e63ed12281/navigation/localisation/src/Cartographie.cpp#L104)):_
Non respect des règles de codages

---

_[navigation/localisation/src/Cartographie.cpp, line 165 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89ZH37LdaGf6_BuUJ6:-K89ZH37LdaGf6_BuUJ7:1746361825) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/0f151e800aa9217b49fa2381851fc2e63ed12281/navigation/localisation/src/Cartographie.cpp#L165)):_
"objectDetection/segments" deux fois (copié/collé malheureux?)

---

_[navigation/path_tracker/src/avoidanceObstacle.cpp, line 326 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89_SLHK8NFK207KUAM:-K89_SLHK8NFK207KUAN:-963143912) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/0f151e800aa9217b49fa2381851fc2e63ed12281/navigation/path_tracker/src/avoidanceObstacle.cpp#L326)):_
double ";;"
et non respect des règles de codages

---

_[navigation/path_tracker/src/dataLaser.cpp, line 43 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89_cj8QqpvNNPRrbeA:-K89_cj97M_kqF8g_AlB:-1669944668) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/0f151e800aa9217b49fa2381851fc2e63ed12281/navigation/path_tracker/src/dataLaser.cpp#L43)):_
Non respect des règles de codages

---

_[navigation/path_tracker/src/dataLaser.cpp, line 52 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89_hjJ_P3WVl9eQTjj:-K89_hjJ_P3WVl9eQTjk:-1669944668) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/0f151e800aa9217b49fa2381851fc2e63ed12281/navigation/path_tracker/src/dataLaser.cpp#L52)):_
Non respect des règles de codages

---

_[navigation/path_tracker/src/dataMapObstacle.cpp, line 107 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89_nxXGYVYqCMjI3pi:-K89_nxXGYVYqCMjI3pj:-1669944668) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/0f151e800aa9217b49fa2381851fc2e63ed12281/navigation/path_tracker/src/dataMapObstacle.cpp#L107)):_
Non respect des règles de codages

---

_[simulation/gazebo_to_ros/src/gazebo_to_ros_node.cpp, line 164 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89aYdz9cToRFPQM7qD:-K89aYe-Soo4H6YYd7pX:-1669944668) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/0f151e800aa9217b49fa2381851fc2e63ed12281/simulation/gazebo_to_ros/src/gazebo_to_ros_node.cpp#L164)):_
Non respect des règles de codages

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38)_

**Comment by ValentinVERGEZ** [comment]
Build fixed

---

Review status: 23 of 28 files reviewed at latest revision, 11 unresolved discussions.

---

_[navigation/localisation/src/Cartographie.cpp, line 40 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89ai5MtdOOm35IRe3Z:-K8A9zLh_2u_fuU3LOit:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fabdf237107de5fe9fdf4ea932d3b2e1252bc19c/navigation/localisation/src/Cartographie.cpp#L40)):_
Done.

---

_[navigation/localisation/src/Cartographie.cpp, line 42 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K892fbUfsiX4jSHGlEi:-K8A9yQLQ6z4K0ksP0J9:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fabdf237107de5fe9fdf4ea932d3b2e1252bc19c/navigation/localisation/src/Cartographie.cpp#L42)):_
Done.

---

_[navigation/localisation/src/Cartographie.cpp, line 61 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K8937Nr3UnVrKME-kIy:-K8AA-KzioPLpB7O5Fte:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fabdf237107de5fe9fdf4ea932d3b2e1252bc19c/navigation/localisation/src/Cartographie.cpp#L61)):_
Done.

---

_[navigation/localisation/src/Cartographie.cpp, line 75 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K8939yVSP4DbUheSwn-:-K8AA02iLlaVk3YE4Asa:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fabdf237107de5fe9fdf4ea932d3b2e1252bc19c/navigation/localisation/src/Cartographie.cpp#L75)):_
Done.

---

_[navigation/localisation/src/Cartographie.cpp, line 104 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89asMlmRo-kFsrJ0Ve:-K8AA0cj3HNwkYK4f1Cp:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fabdf237107de5fe9fdf4ea932d3b2e1252bc19c/navigation/localisation/src/Cartographie.cpp#L104)):_
Done.

---

_[navigation/localisation/src/Cartographie.cpp, line 165 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89ZH37LdaGf6_BuUJ6:-K8AA225TCMAiRd2-5QY:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fabdf237107de5fe9fdf4ea932d3b2e1252bc19c/navigation/localisation/src/Cartographie.cpp#L165)):_
Done.

---

_[navigation/path_tracker/src/avoidanceObstacle.cpp, line 326 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89_SLHK8NFK207KUAM:-K8AA3T-Uqp2myXB28gr:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fabdf237107de5fe9fdf4ea932d3b2e1252bc19c/navigation/path_tracker/src/avoidanceObstacle.cpp#L326)):_
Done.

---

_[navigation/path_tracker/src/dataLaser.cpp, line 43 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89_cj8QqpvNNPRrbeA:-K8AA4FK4QQom78Exkkf:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fabdf237107de5fe9fdf4ea932d3b2e1252bc19c/navigation/path_tracker/src/dataLaser.cpp#L43)):_
Done.

---

_[navigation/path_tracker/src/dataLaser.cpp, line 52 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89_hjJ_P3WVl9eQTjj:-K8AA53AA7uu2CQP85oM:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fabdf237107de5fe9fdf4ea932d3b2e1252bc19c/navigation/path_tracker/src/dataLaser.cpp#L52)):_
Done.

---

_[navigation/path_tracker/src/dataMapObstacle.cpp, line 107 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89_nxXGYVYqCMjI3pi:-K8AA5xX-f7mh_CAUU5E:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fabdf237107de5fe9fdf4ea932d3b2e1252bc19c/navigation/path_tracker/src/dataMapObstacle.cpp#L107)):_
Done.

---

_[simulation/gazebo_to_ros/src/gazebo_to_ros_node.cpp, line 164 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-K89aYdz9cToRFPQM7qD:-K8AA6mjPN-QY-Z1thsL:-499146009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fabdf237107de5fe9fdf4ea932d3b2e1252bc19c/simulation/gazebo_to_ros/src/gazebo_to_ros_node.cpp#L164)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-:-K8AA9jRY9VrpTH12Qox:1257858301)_

**Comment by vianneyPayelle** [comment]
:lgtm: 

---

Review status: 23 of 28 files reviewed at latest revision, 11 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/38#-:-K8AF0SPHoCy85NpniNb:317629051)_

**Pull request merged**
