### PR TITLE
Intégrations devs Robocup 2016 à devel

### PR DESCRIPTION
**Pull request by ValentinVERGEZ**
Tout est dans le titre.

On doit au moins fixer la compil. Pour la revue, ça a déjà été revue (un peu) pour intégration dans robocup-devel, à vous de voir.

---

This change is [Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/117)

### CODE REVIEW

**Comment by tdanel** [comment]
Reviewed 229 of 229 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

_[.travis.yml, line 9 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOLdhjIHfOgyHhyJYq:-KMOLdhjIHfOgyHhyJYr:-481120732) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/.travis.yml#L9)):_

> ``` YAML
>   only:
>     - devel
>     - navigation-devel
> ```

Sûr ?

---

_[common/common_utils/CMakeLists.txt, line 146 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOLvHzas2ww9ve6Lup:-KMOLvHzas2ww9ve6Luq:-1037325262) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/common_utils/CMakeLists.txt#L146)):_

> ``` CMake
> 
> ## Declare a C++ executable
> # add_executable(zoneSizeCalcul_node src/zoneSizeCalcul_node.cpp)
> ```

Un node dans les common ?

---

_[common/common_utils/include/common_utils/zone.h, line 48 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOMJmN_Db2TeYUj8hW:-KMOMJmN_Db2TeYUj8hX:-72012138) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/common_utils/include/common_utils/zone.h#L48)):_

> ``` objc
> }
> 
> inline int getArea(const geometry_msgs::Pose2D &m, float zone_width = 1.96, float zone_height = 1.5)
> ```

A remettre à 2.0

---

_[common/common_utils/src/zoneSizeCalcul_node.cpp, line 2 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOMe6Ha5e_PbAtY0d0:-KMOMe6Ha5e_PbAtY0d1:1946602253) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/common_utils/src/zoneSizeCalcul_node.cpp#L2)):_

> ``` cpp
> /**
>  * \file        simple_cloud_laser_plugin.cpp
> ```

Copier / coller 

---

_[common/common_utils/src/zoneSizeCalcul_node.cpp, line 62 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOMpodXh4mQazbyVSE:-KMOMpodXh4mQazbyVSF:-501512021) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/common_utils/src/zoneSizeCalcul_node.cpp#L62)):_

> ``` cpp
>     }
> 
>     float zone_width = (maxX-minX)/6.0;
> ```

6 et 4 devrait être des paramètres aussi, le nombre de zones en hauteur et en largeur

---

_[common/geometry_utils/include/geometry_utils/geometry_utils.h, line 51 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMON9YubhNiwk2Bkqx5:-KMON9YubhNiwk2Bkqx6:-535925319) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/geometry_utils/include/geometry_utils/geometry_utils.h#L51)):_

> ``` objc
> 
> geometry_msgs::Pose2D changeFrame(const geometry_msgs::Pose2D &p, const tf::StampedTransform &transform);
> geometry_msgs::Pose2D machineToMapFrame(const geometry_msgs::Pose2D &p, const geometry_msgs::Pose2D &poseMachine);
> ```

A génériser (je ne sais pas si ça se dit mais bon ^^)

---

_[common/occupancy_grid_utils/package.xml, line 48 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMONbFFutVzzzp1URfg:-KMONbFGt5CkIEWLgTkS:-1966855110) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/occupancy_grid_utils/package.xml#L48)):_

> ``` XML
>   <build_depend>rospy</build_depend>
>   <build_depend>std_msgs</build_depend>
>   <build_depend>deplacement_msg</build_depend>
> ```

Peut-être le mettre en anglais mais bon, ça se fera cet été

---

_[common/occupancy_grid_utils/include/occupancy_grid_utils/shape/Shape.h, line 33 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOOdXKZNESqjIqpi8y:-KMOOdXLwCR3lq02AFAy:-1046611214) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/occupancy_grid_utils/include/occupancy_grid_utils/shape/Shape.h#L33)):_

> ``` objc
> 
>     virtual void draw(nav_msgs::OccupancyGrid &grid, int max_value=100) = 0;
>     virtual void draw(deplacement_msg::OccupancyGridFloat &grid, int max_value=100){} // TODO factoriser ce code
> ```

factoriser ou templater ?

---

_[common/occupancy_grid_utils/src/occupancy_grid_utils.cpp, line 252 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOOqtW83cMbovQcKDX:-KMOOqtW83cMbovQcKDY:632277173) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/occupancy_grid_utils/src/occupancy_grid_utils.cpp#L252)):_

> ``` cpp
> }
> 
> bool checkCircle(const geometry_msgs::Pose2D &req, double window, const nav_msgs::OccupancyGrid &grid, geometry_msgs::Pose2D &foundPose)
> ```

Sûrement améliorable

---

_[common/occupancy_grid_utils/src/grid_fusion/basic_fusion.cpp, line 40 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOOzOZYr5KSR4Vce3q:-KMOOzOZYr5KSR4Vce3r:1129875925) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/occupancy_grid_utils/src/grid_fusion/basic_fusion.cpp#L40)):_

> ``` cpp
>     return (info1.width == info2.width &&
>             info1.height == info2.height &&
>             std::abs(info1.origin.position.x - info2.origin.position.x) < 0.00001 &&
> ```

magiiiiccccc number !

---

_[common/occupancy_grid_utils/src/shape/Circle.cpp, line 74 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOPAhsVyDObOrO-eEq:-KMOPAhsVyDObOrO-eEr:1823815851) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/occupancy_grid_utils/src/shape/Circle.cpp#L74)):_

> ``` cpp
> }
> 
> void Circle::draw(deplacement_msg::OccupancyGridFloat &grid, int max_value)
> ```

La flemme ?

---

_[hardware/gripper/src/gripper_node.cpp, line 3 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOP_DXrcPN0yeQsE8s:-KMOP_DXrcPN0yeQsE8t:-59734773) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/hardware/gripper/src/gripper_node.cpp#L3)):_

> ``` cpp
> #include <ros.h>
> #include <gripper_msg/SetGripper.h>
> #include <gripper_msg/GripperStatus.h>
> ```

Pas dernière version !!!

---

_[manager/executeur_taches/CMakeLists.txt, line 208 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOPqAO2apLDk1tizUu:-KMOPqAPavVQTZckHRv2:257553050) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/manager/executeur_taches/CMakeLists.txt#L208)):_

> ``` CMake
> # Test final_approach
> add_executable(
>   fake_finalApproachingClient
> ```

Fake à supprimer ?

---

_[manager/executeur_taches/src/reportAllMachines_node.cpp, line 22 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMORFPX8wShHVsoFTd0:-KMORFPYwTcebDL5MS7U:-2009700722) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/manager/executeur_taches/src/reportAllMachines_node.cpp#L22)):_

> ``` cpp
> using namespace std;
> 
> bool isMyTeam(int id, int teamColor)
> ```

A mettre dans types.h dans common ?

---

_[manager/generateur_taches/src/gameState.cpp, line 15 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMORijPyqcFcFRutyNK:-KMORijPyqcFcFRutyNL:-930531659) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/manager/generateur_taches/src/gameState.cpp#L15)):_

> ``` cpp
> 
> GameState::GameState():
>     m_state(0),
> ```

Peut-être utiliser les "vraies" valeurs de GameState.msg

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117)_

**Comment by tdanel** [comment]
Un peu lourd à lire :P j'ai pas vraiment regardé les trucs qui fonctionnaient du style la navigation ^^ Ya du boulot en tout cas

---

Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-:-KMOVfbjUjmtRFnIb6fE:-943381133)_

**Comment by ValentinVERGEZ** [comment]
Hallelujah ...
Et si on se faisait une issue de cleanup et qu'on le faisait au fil de l'été sur la branche devel, t'en penses quoi Thomas? :innocent:

**Comment by vcoelen** [comment]
Ce que moi j'en pense, c'est que ça devrait être une priorité de traiter et nettoyer cette PR, plutôt que de partir sur de nouveaux développements (ex renommage de approche_finale en docking, ça n'était clairement pas une urgence et ça rajoute une nouvelle branche alors qu'il y en a plein à fermer et traiter) 
Si vous souhaiter, travailler pendant les vacances, faites ça, pas d'ajout/modification non urgente/discutée, s'il vous plaît, c'est déjà suffisamment le bazar...
Et je ne suis pas trop pour créer une nouvelle issue, on a tendance à ne pas s'en occuper

**Comment by vcoelen** [comment]
J'essaierai de faire une revue complète. Là j'ai juste pris le temps de répondre aux commentaires de Thomas, quand ça concernait plus ou moins mon travail

---

Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

_[common/common_utils/CMakeLists.txt, line 146 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOLvHzas2ww9ve6Lup:-KMQraAiuu0V9Aw7IbzY:-1051330983) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/common_utils/CMakeLists.txt#L146)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> Un node dans les common ?
> </details>
> Il est commenté et n'a pas été implémente jusqu'au bout, il faudra soit le supprimer soit le terminer
> Techniquement, il y a déjà le node LaserScan_to_pcl en common :)

---

_[common/common_utils/include/common_utils/zone.h, line 48 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOMJmN_Db2TeYUj8hW:-KMQsJqcrAiG9f6fzqdY:-485709910) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/common_utils/include/common_utils/zone.h#L48)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> A remettre à 2.0
> </details>
> A paramétrer (launchfile ou yaml) surtout en fonction de si on lance sur simulateur ou en réel 

---

_[common/common_utils/src/zoneSizeCalcul_node.cpp, line 62 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOMpodXh4mQazbyVSE:-KMQskeH7bqjfgfqdQN-:129691744) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/common_utils/src/zoneSizeCalcul_node.cpp#L62)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> 6 et 4 devrait être des paramètres aussi, le nombre de zones en hauteur et en largeur
> </details>
> Note au passage : ce code n'a pas été testé, je ne me souvient pas comment il a atterri dans cette branche??

---

_[common/geometry_utils/include/geometry_utils/geometry_utils.h, line 51 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMON9YubhNiwk2Bkqx5:-KMQtApcA2jYoiwNdpUx:1275268229) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/geometry_utils/include/geometry_utils/geometry_utils.h#L51)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> A génériser (je ne sais pas si ça se dit mais bon ^^)
> </details>
> Oui et surtout le machineToMapFrame laisse supposer que c'est un code spécifique aux machines alors qu'en fait c'est une transformation applicable à toute pose2D

---

_[common/occupancy_grid_utils/include/occupancy_grid_utils/shape/Shape.h, line 33 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOOdXKZNESqjIqpi8y:-KMQtbEAGukP5BNiN0a2:2025781627) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/occupancy_grid_utils/include/occupancy_grid_utils/shape/Shape.h#L33)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> factoriser ou templater ?
> </details>
> Ou supprimer, à voir. 
> C'était du code pour la méthode d'évitement par flux de gradient qui n'est plus utilisée.

---

_[common/occupancy_grid_utils/src/grid_fusion/basic_fusion.cpp, line 40 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOOzOZYr5KSR4Vce3q:-KMQu8CaUV7ha0DW87Eu:-338597900) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/occupancy_grid_utils/src/grid_fusion/basic_fusion.cpp#L40)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> magiiiiccccc number !
> </details>
> Oui, clairement. Au delà de ça, c'est du code qui ne devrait pas être dans cette branche (et c'est toi qui l'avait accepté :p)

---

_[common/occupancy_grid_utils/src/shape/Circle.cpp, line 74 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-KMOPAhsVyDObOrO-eEq:-KMQuYiSch6UAz2eUkjv:303929481) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/a09e5bb80cb37596a1778c3471bd35033fce3b71/common/occupancy_grid_utils/src/shape/Circle.cpp#L74)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> La flemme ?
> </details>
> non, pas terminé. Ou préparé, mais pas besoin, au final

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-:-KMQuzxFC5XUl8C3NvOv:-305026219)_

**Comment by tdanel** [comment]
:lgtm:

---

Review status: 152 of 271 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/117#-:-KT_-5DmJYR8Fsng0Ed_:bg7igk9)_

**Pull request merged**
