### PR TITLE
Work/valentin/simulator explo/globalsfix and tests

### PR DESCRIPTION
**Pull request by ValentinVERGEZ**
PR de l'Exploration "fonctionnelle".

Ce coup-ci vous pouvez relire et vous lâcher dans les remarques. Enjoy.

[Review on Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/54)

### CODE REVIEW

**Comment by tdanel** [comment]
_[manager/executeur_taches/include/ExploInfoSubscriber.h, line 35 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMeVHuecfG36QeAqEr:-KAMeVHvrpjxtjMlto-D:-392032151) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/9d0534e481b861713321844dce0d12fe51bd74dd/manager/executeur_taches/include/ExploInfoSubscriber.h#L35)):_
m_type
m_zone 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[manager/executeur_taches/include/Machine.h, line 56 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMf3xdNFkt82OAk8ny:-KAMf3xeikPwnCb_ySKs:-33357578) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/include/Machine.h#L56)):_
const geometry_msgs::Pose2D &pt_dest ?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[manager/executeur_taches/src/ExploInfoSubscriber.cpp, line 26 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMfKZRZ5slU0J0DM-e:-KAMfKZRZ5slU0J0DM-f:-1872799730) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/ExploInfoSubscriber.cpp#L26)):_
accolade + à la ligne nan ?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[manager/executeur_taches/src/GtServerSrv.cpp, line 28 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMgAsWOZcPpOvajKOh:-KAMgAsWOZcPpOvajKOi:-1301500637) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/GtServerSrv.cpp#L28)):_
const & ?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[manager/executeur_taches/src/GtServerSrv.cpp, line 61 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMgScZ9JCa7mSdZfN7:-KAMgScZ9JCa7mSdZfN8:1691103463) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/GtServerSrv.cpp#L61)):_
vraiment utile le define pour 2 utilisations ?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[manager/executeur_taches/src/GtServerSrv.cpp, line 95 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMgaBIP9lPccIprOba:-KAMgaBIP9lPccIprObb:-446191501) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/GtServerSrv.cpp#L95)):_
TODO dans une PR ? finis le boulot :P

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[manager/executeur_taches/src/GtServerSrv.cpp, line 242 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMgvtTjJGjbakDgDJx:-KAMgvtUZ3A26eCQcWI7:527458546) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/GtServerSrv.cpp#L242)):_
falltrhough what ?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[manager/executeur_taches/src/GtServerSrv.cpp, line 263 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMh6Am-OdCXUmdrzk-:-KAMh6Am-OdCXUmdrzk0:1606378997) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/GtServerSrv.cpp#L263)):_
int(variable) != (int)variable 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[manager/executeur_taches/src/Machine.cpp, line 74 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMhQy-Oe4WrlBi5ncJ:-KAMhQy-Oe4WrlBi5ncK:678173543) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/Machine.cpp#L74)):_
{

}

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[manager/executeur_taches/src/main.cpp, line 36 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMhYT_2wWZNIXh8Fu0:-KAMhYT_2wWZNIXh8Fu1:-238199215) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/main.cpp#L36)):_
www.meatspin.fr

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[manager/executeur_taches/src/main.cpp, line 33 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMhaqsEvTuCnBhaknf:-KAMhaqsEvTuCnBhakng:-1344955695) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/main.cpp#L33)):_
héritage de Sandra à garder absolument :P

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[manager/generateur_taches/src/main_node.cpp, line 80 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMhtxd2wyCxeBI0zWv:-KAMhtxd2wyCxeBI0zWw:482376919) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/generateur_taches/src/main_node.cpp#L80)):_
elapsed

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[manager/generateur_taches/src/main_node.cpp, line 80 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMhxSYJECOGQ8CF4Pq:-KAMhxSYJECOGQ8CF4Pr:-2119022306) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/generateur_taches/src/main_node.cpp#L80)):_
int(time)

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[manager/generateur_taches/src/srvorder.cpp, line 5 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMi6MFYqUjp6cboUrB:-KAMi6MG0O5V0hu_YI__:1073633738) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/generateur_taches/src/srvorder.cpp#L5)):_
SrvOrder nan ? 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
_[traitement_image/ar_tag/launch/alvar_simu.launch, line 5 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMih2qEPGiwhh8tTsR:-KAMih2rTdsI8KYhGoEt:120508835) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/traitement_image/ar_tag/launch/alvar_simu.launch#L5)):_
camera/tower_camera ou plus simplement camera/tower

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Comment by tdanel** [comment]
Attention aux normes sur les noms de fichiers
if 
{

}
et const &

:lgtm: 

---

Review status: 0 of 23 files reviewed at latest revision, 15 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-:-KAMisfhL8JmDLArn9na:1276167889)_

**Comment by ValentinVERGEZ** [comment]
Ok pour les remarques. Je vais toutes les traiter pour voir si je les approuve ou non.

Thomas, tu l'as p-e fait exprès, mais sinon sache que tu peux parfaitement faire un publish de tous tes commentaires en une seule fois plutôt que comme ici où tu as publié commentaire par commentaire.

---

Review status: 0 of 23 files reviewed at latest revision, 15 unresolved discussions, all commit checks successful.

---

_[manager/executeur_taches/include/ExploInfoSubscriber.h, line 35 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMeVHuecfG36QeAqEr:-KAP2IU92HaM_ZqP_3bH:-357533532) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/9d0534e481b861713321844dce0d12fe51bd74dd/manager/executeur_taches/include/ExploInfoSubscriber.h#L35)):_
Yep -> @SandraHage 

---

_[manager/executeur_taches/include/Machine.h, line 56 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMf3xdNFkt82OAk8ny:-KAOyVvuQaD5MapQGvqA:-357533532) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/include/Machine.h#L56)):_
Yep -> @SandraHage 

---

_[manager/executeur_taches/src/ExploInfoSubscriber.cpp, line 26 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMfKZRZ5slU0J0DM-e:-KAOyfvJbMfDcH3eQ8sf:-1983426397) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/ExploInfoSubscriber.cpp#L26)):_
Plutôt un switch case --> @SandraHage 

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 28 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMgAsWOZcPpOvajKOh:-KAOypYPfqHvWZ3zHIIw:-357533532) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/GtServerSrv.cpp#L28)):_
Yep -> @SandraHage 

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 61 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMgScZ9JCa7mSdZfN7:-KAOytwktxV4oCInjCdR:-1635627288) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/GtServerSrv.cpp#L61)):_
Oui, ça évite tous simplement le magic number qu'on ne sait plus d'où il vient à la relecture. J'aurais pu utiliser une variable const aussi ...

Tu noteras le `#undef` en fin de fonction qui limite le scope de ce define.
Je t'avoue que c'est surtout une habitude pour le C et que c'est probablement une mauvaise pratique pour le C++. En tout cas ça reste préférable à mes yeux que le magic number.

Je te laisse indiquer la bonne pratique C++ pour @SandraHage qui va reprendre le boulot. 

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 95 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMgaBIP9lPccIprOba:-KAOzewe18jVKbFGXAVx:-96630542) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/GtServerSrv.cpp#L95)):_
Non, une issue est ouverte pour faire les choses proprement. C'était pas la vocation de ce dev,  @SandraHage va reprendre le témoin sur l’exécuteur. 

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 242 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMgvtTjJGjbakDgDJx:-KAOzvPg3kVRDIaJ2_0d:1347569681) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/GtServerSrv.cpp#L242)):_
C'est pour expliciter le comportement du case qui continuera dans le case suivant faute de break ou de return. Parfois l'absence de break ou de return est une erreur, avec ces commentaires le relecteur (toi ou un autre gars dans quelques mois) saura que ça a été fait sciemment.

Je peux l'ajouter à la normalisation du code si tu veux. Plutôt comme une bonne pratique qu'en tant qu'obligation. 

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 263 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMh6Am-OdCXUmdrzk-:-KAP1DI78VtdwP7ZJPCP:-2067875113) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/GtServerSrv.cpp#L263)):_
Tu veux dire (int)(var.field) != (int)var.field ? Si oui, si, l'opérateur . est prioritaire sur l'opérateur de casting.

Ceci dit, je ne sais pas pourquoi elle a besoin de caster.

-> @SandraHage 

---

_[manager/executeur_taches/src/Machine.cpp, line 74 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMhQy-Oe4WrlBi5ncJ:-KAP2yKXgXiHPjWP5Fti:-357533532) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/Machine.cpp#L74)):_
Yep -> @SandraHage 

---

_[manager/executeur_taches/src/main.cpp, line 33 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMhaqsEvTuCnBhaknf:-KAP396t_pKCM1u01lDk:1836845291) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/main.cpp#L33)):_
ARF
-> @SandraHage 

---

_[manager/executeur_taches/src/main.cpp, line 36 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMhYT_2wWZNIXh8Fu0:-KAP3Ff0trpWe9_L_Vdn:-1661814657) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/main.cpp#L36)):_
Je te déteste

---

_[manager/generateur_taches/src/main_node.cpp, line 80 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMhtxd2wyCxeBI0zWv:-KAP3mvftyJ3Ir5Cqglf:1440979045) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/generateur_taches/src/main_node.cpp#L80)):_
@cyrilsmg  : Je te le laisse. Je ne vais pas faire un commit pour ça.

---

_[manager/generateur_taches/src/main_node.cpp, line 80 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMhxSYJECOGQ8CF4Pq:-KAP3yCMSZYxOGqr60O9:2096065907) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/generateur_taches/src/main_node.cpp#L80)):_
??? Je ne te suis pas

---

_[manager/generateur_taches/src/srvorder.cpp, line 5 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMi6MFYqUjp6cboUrB:-KAP432CNWCZrHxewEb4:-1803983712) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/generateur_taches/src/srvorder.cpp#L5)):_
Yep -> @cyrilsmg 

---

_[traitement_image/ar_tag/launch/alvar_simu.launch, line 5 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMih2qEPGiwhh8tTsR:-KAP4P-hlmrxnbo4ijRT:-1268239116) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/traitement_image/ar_tag/launch/alvar_simu.launch#L5)):_
Ok pour hardware/camera/tower ou camera/tower si on décide de dissocier les images du namespaces hardware.

Modification qui doit être faire en dehors de cette PR ceci dit.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-:-KAOy4BimN2T6f035hi8:1130663107)_

**Comment by SandraHage** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions, all commit checks successful.

---

_[manager/executeur_taches/src/main.cpp, line 33 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54#-KAMhaqsEvTuCnBhaknf:-KAPeZdIz5-hwmwopkXF:-2070481556) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d262855b1d3626820c2125ad2c44f9c92d91c1da/manager/executeur_taches/src/main.cpp#L33)):_
héritage? :O

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/54)_

**Pull request merged**
