### PR TITLE
Work/thomas/fix.get side points

### PR DESCRIPTION
**Pull request by tdanel**
This change is [Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/99)

### CODE REVIEW

**Comment by vcoelen** [comment]
Reviewed 3 of 6 files at r1, 2 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_[common/geometry_utils/src/geometry_utils.cpp, line 54 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/99#-KL_waYrAAkdW7Xn9iF4:-KL_waYrAAkdW7Xn9iF5:237315953) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/c206c272d499e2dc1cf13c15bfa2eee000e1997a/common/geometry_utils/src/geometry_utils.cpp#L54)):_

> ``` cpp
>   double yaw = poseMachine.theta;
>   result.x     = p.x*cos(yaw) - p.y*sin(yaw) + poseMachine.x;
>   result.y     = p.x*sin(yaw) + p.y*cos(yaw) + poseMachine.y;
> ```

Factoriser le code avec changeFrame

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/99)_

**Comment by vcoelen** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/99)_

**Comment by vcoelen** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/99#-:-KL_xv072PZ7isbHKzKj:1417088721)_

**Comment by ValentinVERGEZ** [comment]
:lgtm:

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/99#-:-KLa0OwI3fEqQmXlDzBl:1417088721)_

**Pull request merged**
