### PR TITLE
Problème résolu sur les départs de chemins dans zone interdite

### PR DESCRIPTION
**Pull request by tdanel**
This change is [Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/61)

### CODE REVIEW

**Comment by vcoelen** [comment]
Reviewed 12 of 19 files at r1.
Review status: 12 of 19 files reviewed at latest revision, 9 unresolved discussions.

---

_[common/occupancy_grid_utils/include/occupancy_grid_utils/occupancy_grid_utils.h, line 49 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIlzz4jQoEj6wXZaX2R:-KIlzz4jQoEj6wXZaX2S:391634682) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/common/occupancy_grid_utils/include/occupancy_grid_utils/occupancy_grid_utils.h#L49)):_

> ``` objc
> geometry_msgs::Pose2D topRight(const nav_msgs::OccupancyGrid &grid, const geometry_msgs::Pose2D &req, double window);
> 
> geometry_msgs::Pose2D checkStartPos(const geometry_msgs::Pose2D &req, double window, const nav_msgs::OccupancyGrid &grid);
> ```

Je pense que checkStartPos ne devrais pas être dans occupancy_grid_utils car c'est une fonction spécifique au noeud pathfinder. Et je me pose la question pour les fonctions topLeft, bottomLeft, topRight.

---

_[common/occupancy_grid_utils/src/occupancy_grid_utils.cpp, line 301 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm0fuEkSjaa2Y_lyTi:-KIm0fuFipIAPwRZgsVO:677844703) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/common/occupancy_grid_utils/src/occupancy_grid_utils.cpp#L301)):_

> ``` cpp
>   bool found = false;
> 
>   if (getCellValue(grid, req) < 100)
> ```

tu testes le centre du cercle ici? Ça devrait être dans checkStartPos.

---

_[common/occupancy_grid_utils/src/occupancy_grid_utils.cpp, line 306 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm05MV1SYq48IbLtHQ:-KIm05MWAtXskrgwJ6MT:-1888502498) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/common/occupancy_grid_utils/src/occupancy_grid_utils.cpp#L306)):_

> ``` cpp
>       foundPose = req;
>   }
>   if (checkRow(grid, topLeft(grid, req, window), window, foundPose))
> ```

else if ?

---

_[common/occupancy_grid_utils/src/occupancy_grid_utils.cpp, line 364 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm1AYBQnf2jYa0J975:-KIm1AYCOaVxMTl9lDi-:-2025647192) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/common/occupancy_grid_utils/src/occupancy_grid_utils.cpp#L364)):_

> ``` cpp
> 
>   bool found = false;
>   double currentWindow = 0.0;
> ```

Du coup tu peux commencer avec currentWindow=grid.info.resolution, sinon tu testes plein de fois et de plein de manières différentes le centre du cercle

---

_[navigation/grid_maker/cfg/field.yaml, line 9 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm1mw_TSvq-9UciIO7:-KIm1mwaOvyXLlA4Yapq:-1580530789) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/navigation/grid_maker/cfg/field.yaml#L9)):_

> ``` YAML
>     margin: 0.25
>     gradient:
>         distance: 0
> ```

Est-ce que tu peux remettre 0.35 une fois les tests terminés. C'est pas indispensable, c'est juste pour garder la config par défaut

---

_[navigation/localisation/src/landmarks_extraction_node.cpp, line 21 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm22wc-gyu9DIHj-IQ:-KIm22wdl11KYA3Yu-kz:1194354669) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/navigation/localisation/src/landmarks_extraction_node.cpp#L21)):_

> ``` cpp
> 
>     // Subscribe to laserScan
>     ros::Subscriber sub_laser  = n.subscribe("/robotino1/hardware/scan", 1, &laserScan::laserCallback, &laserData);
> ```

Il vaut mieux utiliser les namespaces dans les launchFiles

---

_[navigation/localisation/src/LaserScan.cpp, line 78 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm2H8pa_gRCmDj_09r:-KIm2H8pa_gRCmDj_09s:-822046016) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/navigation/localisation/src/LaserScan.cpp#L78)):_

> ``` cpp
>   for (int i=0; i<m_ranges.size(); i++)
>   {
>       if((m_ranges[i] > getRangeMin()) && (m_ranges[i] < getRangeMax()-0.5))
> ```

Magic Number ?

---

_[navigation/localisation/src/odometry_correction_node.cpp, line 72 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm2LSsidxaWn7e_wFQ:-KIm2LSsidxaWn7e_wFR:-1915996714) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/navigation/localisation/src/odometry_correction_node.cpp#L72)):_

> ``` cpp
> 
>     //on souscrit au topic /odom
>     ros::Subscriber sub_odom  = n.subscribe("/robotino1/hardware/odom", 1000, odomCallback);
> ```

Namespace

---

_[navigation/localisation/src/visualisationOK.cpp, line 103 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm2P0fdLgWQiwfMvOI:-KIm2P0fdLgWQiwfMvOJ:-1915996714) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/navigation/localisation/src/visualisationOK.cpp#L103)):_

> ``` cpp
>     segments.points = tabSegments;
> 
>     landmarks.header.frame_id = "robotino1/hardware/odom";
> ```

Namespace

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61)_

**Comment by tdanel** [comment]
Review status: 12 of 19 files reviewed at latest revision, 9 unresolved discussions.

---

_[common/occupancy_grid_utils/include/occupancy_grid_utils/occupancy_grid_utils.h, line 49 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIlzz4jQoEj6wXZaX2R:-KIm6wcj2t848yz1jQW1:-1006614875) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/common/occupancy_grid_utils/include/occupancy_grid_utils/occupancy_grid_utils.h#L49)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> Je pense que checkStartPos ne devrais pas être dans occupancy_grid_utils car c'est une fonction spécifique au noeud pathfinder. Et je me pose la question pour les fonctions topLeft, bottomLeft, topRight.
> </details>
> Ce sont des opérations sur des nav_msgs::OccupancyGrid donc ça me semblait normal de les mettre ici ^^

---

_[common/occupancy_grid_utils/src/occupancy_grid_utils.cpp, line 301 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm0fuEkSjaa2Y_lyTi:-KIm79zBGWTk9mn3-tsb:-902049407) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/common/occupancy_grid_utils/src/occupancy_grid_utils.cpp#L301)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> tu testes le centre du cercle ici? Ça devrait être dans checkStartPos.
> </details>
> Pas faux

---

_[common/occupancy_grid_utils/src/occupancy_grid_utils.cpp, line 306 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm05MV1SYq48IbLtHQ:-KIm7Bt_jbIudQszIh2R:160385022) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/common/occupancy_grid_utils/src/occupancy_grid_utils.cpp#L306)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> else if ?
> </details>
> Oui

---

_[navigation/grid_maker/cfg/field.yaml, line 9 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm1mw_TSvq-9UciIO7:-KIm7Dm3HVzAuPn19N0s:69324860) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/navigation/grid_maker/cfg/field.yaml#L9)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> Est-ce que tu peux remettre 0.35 une fois les tests terminés. C'est pas indispensable, c'est juste pour garder la config par défaut
> </details>
> Bon techniquement la PR n'est pas pour ça mais oui ^^ ce sont des reliquats de ce que j'ai pu faire 

---

_[navigation/localisation/src/landmarks_extraction_node.cpp, line 21 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm22wc-gyu9DIHj-IQ:-KIm7LvSKvaTCkHM7H3C:1668613943) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/navigation/localisation/src/landmarks_extraction_node.cpp#L21)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> Il vaut mieux utiliser les namespaces dans les launchFiles
> </details>
> Certes

---

_[navigation/localisation/src/LaserScan.cpp, line 78 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm2H8pa_gRCmDj_09r:-KIm7WAFj5dCcPJ_yvZb:2140968889) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/navigation/localisation/src/LaserScan.cpp#L78)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> Magic Number ?
> </details>
> A cause de gazebo qui donne des points quand même quand le laser ne touche rien, ma détection de segment fait des segments sur les arcs de cercle du laser 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61)_

**Comment by ValentinVERGEZ** [comment]
Vous voulez du ci-travis sur les PR navigation-devel ?

**Comment by tdanel** [comment]
Pourquoi pas

<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> Vous voulez du ci-travis sur les PR navigation-devel ?
> </details>

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-:-KIm8HpcipWY-xpEnZHA:-709970175)_

**Comment by vcoelen** [comment]
Non pas forcement de ci-travis, en plus pour l'instant la compilation sur navigation-devel est cassée

<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> Pourquoi pas
> </details>

---

Reviewed 6 of 8 files at r2.
Review status: 16 of 22 files reviewed at latest revision, 7 unresolved discussions.

---

_[common/occupancy_grid_utils/include/occupancy_grid_utils/occupancy_grid_utils.h, line 49 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIlzz4jQoEj6wXZaX2R:-KImTVghYJ213n_dPl_L:1687047361) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/common/occupancy_grid_utils/include/occupancy_grid_utils/occupancy_grid_utils.h#L49)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> Ce sont des opérations sur des nav_msgs::OccupancyGrid donc ça me semblait normal de les mettre ici ^^
> </details>
> Pas tout à fais, les bibliothèques communes servent à mettre en commun du code utile pour plusieurs personnes. Pour l'occupancy_grid_utils, on ne veut pas y mettre tout le code qui s'y rapporte mais plutôt le code qui facilite la manipulation des nav_msgs::OccupancyGrid, pas les codes spécifiques aux noeuds.

---

_[common/occupancy_grid_utils/src/occupancy_grid_utils.cpp, line 306 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm05MV1SYq48IbLtHQ:-KImU_KVjxpb1N1_cyxj:-1972701974) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/common/occupancy_grid_utils/src/occupancy_grid_utils.cpp#L306)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> Oui
> </details>
> En dessous aussi du coup :)

---

_[navigation/grid_maker/cfg/field.yaml, line 9 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm1mw_TSvq-9UciIO7:-KImUiSEPGSaHg6BLifv:1531502505) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/navigation/grid_maker/cfg/field.yaml#L9)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> Bon techniquement la PR n'est pas pour ça mais oui ^^ ce sont des reliquats de ce que j'ai pu faire 
> </details>
> Oui je suis d'accord, c'était pas bloquant pour la PR mais juste pour chipoter ^^

---

_[navigation/localisation/src/LaserScan.cpp, line 78 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm2H8pa_gRCmDj_09r:-KImVL1-diQYrU-mOqh1:-280622964) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/navigation/localisation/src/LaserScan.cpp#L78)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> A cause de gazebo qui donne des points quand même quand le laser ne touche rien, ma détection de segment fait des segments sur les arcs de cercle du laser 
> </details>
> J'ai pas bien compris. Mais dans tous les cas si ça n'est pas évident et que c'est une adaptation à cause d'un problème quelconque c'est indispensable d'expliquer en commentaire du code pourquoi ce -0.5

---

_[navigation/localisation/src/odometry_correction_node.cpp, line 72 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-KIm2LSsidxaWn7e_wFQ:-KImVvr-nDO1CO5a012A:291422122) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4e5a7b3cac51d2ef4ab108eae305264130edde11/navigation/localisation/src/odometry_correction_node.cpp#L72)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> Namespace
> </details>
> Tu ne veux pas modifier celui-là :'(

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/61#-:-KImWO4FLbbXpYi8nAKV:-288325566)_

**Comment by ValentinVERGEZ** [comment]
Bon, y'a du CI-Travis mais la branche n'étant pas protégée c'est non bloquant.
Je peux laisser ?

**Comment by vcoelen** [comment]
@ValentinVERGEZ oui si on fixe rapidement, sinon c'est casse pied

**Comment by tdanel** [comment]
Valentin avec ta modif sur le trackpath le build a pété sur le hotfix ^^

**Comment by ValentinVERGEZ** [comment]
Tu parles de ça : https://github.com/PyroTeam/robocup-pkg/pull/62 ?

Et ou est-ce qu'on peut voir le build péter ?

**Comment by vcoelen** [comment]
Quelques minutes après le dernier fix, on a même pas le temps de faire une review, or 
n.subscribe("/hardware/odom", 1000, odomCallback); 
est faux (un '/' en trop): 
n.subscribe("hardware/odom", 1000, odomCallback);
La différence est subtile, mais c'est ce qui permet d'utiliser les namespaces.
Et on avait aussi parlé de déplacer des fonctions telles que 'checkStartPos'.
Pourquoi on met des PR si la personne qui a ouvert la PR, la merge sans attendre une validation?

**Comment by tdanel** [comment]
On avait parlé oui, pris une décision non.

**Comment by vcoelen** [comment]
Donc il ne fallait pas prendre la décision de merger

**Pull request merged**
