### PR TITLE
Feature/communication/inter robots

### PR DESCRIPTION
**Pull request by vcoelen**
Après une demande répétée et une attente insoutenable ^^, PR pour réintégration de la branche communication. 
Fonctionnalités : 
- ajout du message beacon
- échange de Topics
- communication chiffrée

(La branche peut être supprimée)

---

This change is [Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/132)

### CODE REVIEW

**Comment by tdanel** [comment]
Reviewed 1 of 8 files at r1, 7 of 26 files at r4, 2 of 9 files at r5, 8 of 18 files at r6, 2 of 2 files at r7, 6 of 10 files at r8, 12 of 12 files at r9.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

_[communication/robot_comm/include/udpToTopicBeacon.h, line 48 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7IFAiNwPu7dR9VT8C:-KU7IFAjWq7sUGU04WTT:bq0lq96) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpToTopicBeacon.h#L48)):_

> ``` objc
>     robot.nb_robot = 0;
>     robot.ip = "";
>     robot.last_time_active.sec = 0;
> ```

better way to do that BIATCH :P

---

_[communication/robot_comm/include/udpToTopicBeacon.h, line 76 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7IR81OMaQ4LhAlzib:-KU7IR81OMaQ4LhAlzic:b-5acyo7) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpToTopicBeacon.h#L76)):_

> ``` objc
>     m_activeRobots[m.nb_robot()].nb_robot = m.nb_robot();
>     Time* time = m.mutable_timestamp();
>     m_activeRobots[m.nb_robot()].last_time_active.sec = time->sec();
> ```

same thing

---

_[communication/robot_comm/launch/robotComm.launch, line 7 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7IjWW8zKogv9SKahr:-KU7IjWW8zKogv9SKahs:b-k7m072) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/launch/robotComm.launch#L7)):_

> ``` XML
>     <param name="portIn" value="5001" />
>     <param name="portOut" value="5001" />
>     <param name="adresseIP" value="127.0.0.255" />
> ```

ipAdress

---

_[communication/robot_comm/src/encryptUtils.cpp, line 70 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7K9sFPkKubk2ODhrI:-KU7K9sFPkKubk2ODhrJ:boxaygg) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/src/encryptUtils.cpp#L70)):_

> ``` cpp
> {
>     unsigned char decryptedMsg[encryptedMessage.size()+16];
>     //Buffer_type encryptedMessage = .push_back(0);
> ```

some cleaning to do

---

_[communication/robot_comm/src/encryptUtils.cpp, line 91 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7M8mzB_EpNcSp6Z4o:-KU7M8mzB_EpNcSp6Z4p:b-yj8wm) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/src/encryptUtils.cpp#L91)):_

> ``` cpp
> 
>   /* Create and initialise the context */
>   if(!(ctx = EVP_CIPHER_CTX_new())) handleErrors();
> ```

pas sur la meme ligne enfin ! :P

---

_[communication/robot_comm/src/encryptUtils.cpp, line 142 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7MDXg_wicNNeFFmlw:-KU7MDXhRJxPGUOzeJYY:b3kre) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/src/encryptUtils.cpp#L142)):_

> ``` cpp
>    * IV size for *most* modes is the same as the block size. For AES this
>    * is 128 bits */
>    std::cout << key << std::endl;
> ```

?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132)_

**Comment by ValentinVERGEZ** [comment]
Reviewed 2 of 26 files at r4, 3 of 18 files at r6, 1 of 2 files at r7, 3 of 10 files at r8, 11 of 12 files at r9.
Review status: all files reviewed at latest revision, 24 unresolved discussions, some commit checks failed.

---

_[communication/robot_comm/README.md, line 2 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7Hmmm8tF-BzxjoaqT:-KU7Hmmm8tF-BzxjoaqU:bqedhvq) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/README.md#L2)):_

> ``` Markdown
> robot_comm
> ==============
> ```

Hey, y'a trop de '=', c'est pas beau :-1: 

---

_[communication/robot_comm/include/messageCatalog.h, line 9 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7IOs3HQDei71UlP4j:-KU7IOs4ZvCtOHjy3Rrr:b-144bxu) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/messageCatalog.h#L9)):_

> ``` objc
>  *               Tissot Elise (elise.tissot@polytech-lille.net)
>  * \date         2015-05-22
>  * \copyright    PyroTeam, Polytech-Lille
> ```

ARPL Maintenant, non ? (Moi même je ne sais plus)

---

_[communication/robot_comm/include/messageCatalog.h, line 78 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7IZlh_-KJgT5rH0qw:-KU7IZlh_-KJgT5rH0qx:buz81x2) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/messageCatalog.h#L78)):_

> ``` objc
> }
> 
> #endif
> ```

// MESSAGECATALOG_h

---

_[communication/robot_comm/include/topicToUdpEntry.h, line 46 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7IoolPyTAt-Pv2kuH:-KU7IoomLzhYg_gXJw4k:b48cggt) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/topicToUdpEntry.h#L46)):_

> ``` objc
>         //send it via UdpPeer
>         m_udpPeer->send(proto_msg);
>         //std::cout << "Send udp msg" <<std::endl;
> ```

A supprimer

---

_[communication/robot_comm/include/udpPeer.h, line 9 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7IxKIIAxoqGCPXgYc:-KU7IxKJLYrFlluwQvuq:bb6s3ua) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpPeer.h#L9)):_

> ``` objc
>  *               Tissot Elise (elise.tissot@polytech-lille.net)
>  * \date         2015-04-06
>  * \copyright    PyroTeam, Polytech-Lille
> ```

ARPL

---

_[communication/robot_comm/include/udpPeer.h, line 45 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7JJUCnbrf26PGH5fx:-KU7JJUCnbrf26PGH5fy:bgk1c27) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpPeer.h#L45)):_

> ``` objc
>       int m_portIn;
>       int m_portOut;
>         std::string m_adresseIP;
> ```

address

---

_[communication/robot_comm/include/udpPeer.h, line 56 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7JC2BSHsiFm4Vfpbb:-KU7JC2BSHsiFm4Vfpbc:byp18fd) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpPeer.h#L56)):_

> ``` objc
>   public:
>       void send(std::shared_ptr<google::protobuf::Message>& msg);
>       //void setCrypto(std::vector<unsigned char> key, EncryptUtils::CIPHER_TYPE cipher);
> ```

Remove

---

_[communication/robot_comm/include/udpPeer.h, line 60 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7JOm9SB7NYOVYJfhz:-KU7JOm9SB7NYOVYJfi-:bgk1c27) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpPeer.h#L60)):_

> ``` objc
>       void setCatalog(std::shared_ptr<MessageCatalog> catalog);
> 
>       UdpPeer(boost::asio::io_service& io_service, int portIn, int portOut, std::string adresseIP);
> ```

address

---

_[communication/robot_comm/include/udpPeer.h, line 67 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7IzPKRRv8hHqSc_mP:-KU7IzPKRRv8hHqSc_mQ:b7r5xui) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpPeer.h#L67)):_

> ``` objc
> };
> 
> #endif
> ```

Comment

---

_[communication/robot_comm/include/udpToTopicBeacon.h, line 9 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7JW2laVZsVe2hmvaK:-KU7JW2laVZsVe2hmvaL:b-ojc8gb) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpToTopicBeacon.h#L9)):_

> ``` objc
>  *               Tissot Elise
>  * \date         2015-06-02
>  * \copyright    PyroTeam, Polytech-Lille
> ```

ARPL ... même remarques pour les autres fichiers

"2016, Association de Robotique de Polytech Lille All rights reserved"

---

_[communication/robot_comm/include/udpToTopicBeacon.h, line 78 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7LxToXhXNfQHCnQqH:-KU7LxToXhXNfQHCnQqI:b-88s9hw) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpToTopicBeacon.h#L78)):_

> ``` objc
>     m_activeRobots[m.nb_robot()].last_time_active.sec = time->sec();
>     m_activeRobots[m.nb_robot()].last_time_active.nsec = time->nsec();
> 
> ```

Trailing spaces

---

_[communication/robot_comm/include/udpToTopicBeacon.h, line 83 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7LzEHpE8XXDAtRn5V:-KU7LzEHpE8XXDAtRn5W:b-1n941) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpToTopicBeacon.h#L83)):_

> ``` objc
> 
>     /*m_activeRobots_pub = m_nh.advertise<comm_msg::active_robots>("/activeRobots", 1000);
>     m_activeRobots.publish(*rosMsgActiveRobots);*/
> ```

A virer ? Sinon, commentaire pour expliquer

---

_[communication/robot_comm/include/udpToTopicBeacon.h, line 91 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7J_dXBvzMXOhB_feO:-KU7J_dXBvzMXOhB_feP:b-47hf83) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpToTopicBeacon.h#L91)):_

> ``` objc
> }
> 
> #endif
> ```

Comment. Même remarques sur les autres fichiers

---

_[communication/robot_comm/include/udpToTopicEntry.h, line 57 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7MFt3wqMIdlB7l95v:-KU7MFt3wqMIdlB7l95w:bv64b03) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpToTopicEntry.h#L57)):_

> ``` objc
>         std::string name = "/test/";
>         name.append(m.name());
>         ros::Publisher pub = m_nh.advertise<P>(name, 1000);
> ```

1000 nécessaire ?

---

_[communication/robot_comm/src/encryptUtils.cpp, line 60 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7Mafn9a5nt-cxtZr2:-KU7MafobuWhjTPxVAFZ:byp18fd) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/src/encryptUtils.cpp#L60)):_

> ``` cpp
>     getRandomIV(initialisationVector);
>     unsigned char cipherMessage[message.size()+16];
>     //std::cout << m_key.c_str() << std::endl;
> ```

Remove

---

_[communication/robot_comm/src/robotCommNode.cpp, line 42 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7NTOyqhpPHKlz_3R_:-KU7NTOzgIhrUP68yob2:bgk1c27) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/src/robotCommNode.cpp#L42)):_

> ``` cpp
>     nh.param<int>("portOut", portOut, 5001);
>     std::string adresseIP;
>     nh.param<std::string>("adresseIP", adresseIP, "127.0.0.255");
> ```

address

---

_[communication/robot_comm/src/udpPeer.cpp, line 35 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7NjpQ3FXVWANrNWis:-KU7NjpQ3FXVWANrNWit:b-960z4m) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/src/udpPeer.cpp#L35)):_

> /\* Constantes */
> #define TAILLE_BUFFER  1024
> #define CRYPTE         1
> #define NON_CRYPTE     0
> #define CODE          'c'
> #define TAILLE_HEADER 18
> #define DEBUT_IV       2

const

---

_[communication/robot_comm/src/udpPeer.cpp, line 116 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7NwNhgeRYNIqnH3P2:-KU7NwNhgeRYNIqnH3P3:b-f3y74j) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/src/udpPeer.cpp#L116)):_

> /_void UdpPeer::setCrypto(std::vector<unsigned char> key, EncryptUtils::CIPHER_TYPE cipher)
> {
>   m_encryptUtil.setConfig(key, cipher);
> }_/
> Remove

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132)_

**Comment by ValentinVERGEZ** [comment]
Review status: all files reviewed at latest revision, 25 unresolved discussions, some commit checks failed.

---

_[messages/comm_msg/CMakeLists.txt, line 78 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7PQBTTR10_igksA9L:-KU7PQBTTR10_igksA9M:btxaaez) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/messages/comm_msg/CMakeLists.txt#L78)):_

> ## Generate services in the 'srv' folder
> 
> # add_service_files(
> 
> # FILES
> 
> # Service1.srv
> 
> # Service2.srv
> 
> # )

add_service_files(
    FILES
    ReportMachine.srv
    PrepareMachine.srv

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132)_

**Comment by vcoelen** [comment]
Review status: all files reviewed at latest revision, 25 unresolved discussions, some commit checks failed.

---

_[communication/robot_comm/include/udpPeer.h, line 56 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7JC2BSHsiFm4Vfpbb:-KU7U1hmGd5OWkN8Qrcp:b7rdlue) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpPeer.h#L56)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> Remove
> </details>
> idem que cpp, je laisse

---

_[communication/robot_comm/include/udpToTopicBeacon.h, line 83 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7LzEHpE8XXDAtRn5V:-KU7SR1JuL2QLrqUgLqf:bm6r8za) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpToTopicBeacon.h#L83)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> A virer ? Sinon, commentaire pour expliquer
> </details>
> Je ne suis pas sûr je pense que la publication a été supprimé pour des tests, je laisse pour l'instant

---

_[communication/robot_comm/include/udpToTopicEntry.h, line 57 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7MFt3wqMIdlB7l95v:-KU7SyAe7uBD7HA9v5Jp:b2ni8q0) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/include/udpToTopicEntry.h#L57)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> 1000 nécessaire ?
> </details>
> non

---

_[communication/robot_comm/src/udpPeer.cpp, line 35 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7NjpQ3FXVWANrNWis:-KU7QN1aUI4h6AXPGbc1:byb1lxe) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/src/udpPeer.cpp#L35)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> > /\* Constantes */
> > #define TAILLE_BUFFER  1024
> > #define CRYPTE         1
> > #define NON_CRYPTE     0
> > #define CODE          'c'
> > #define TAILLE_HEADER 18
> > #define DEBUT_IV       2
> 
> const
> </details>
> D'accord, je les laisse pour l'instant

---

_[communication/robot_comm/src/udpPeer.cpp, line 116 at r9](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7NwNhgeRYNIqnH3P2:-KU7Qxu9uuJNxp1-WKIP:b3aswl0) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/df239ea49ceddd863ee135023f89c30d1b8cd15c/communication/robot_comm/src/udpPeer.cpp#L116)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> > /_void UdpPeer::setCrypto(std::vector<unsigned char> key, EncryptUtils::CIPHER_TYPE cipher)
> > {
> >     m_encryptUtil.setConfig(key, cipher);
> > }_/
> > Remove
> > </details>
> > Je laisse pour l'instant, la raison de la mise en commentaire est inconnue

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132)_

**Comment by ValentinVERGEZ** [comment]
:lgtm:

---

Reviewed 20 of 20 files at r10.
Review status: all files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

_[communication/robot_comm/include/udpToTopicBeacon.h, line 78 at r10](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-KU7VHTyyBXvXUopAS4X:-KU7VHTyyBXvXUopAS4Y:bs9ev2b) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/55ab0bf71f77a6910272fff7ebf8d23ff2ff0823/communication/robot_comm/include/udpToTopicBeacon.h#L78)):_

> ``` objc
>     m_activeRobots[m.nb_robot()].last_time_active.nsec = time->nsec();
> 
>     //Publication des messages désaxtivée temporairement
> ```

désactivée

non bloquant

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-:-KU7W6odXyRxIV0k1yBn:bnfp4nl)_

**Comment by tdanel** [comment]
:lgtm:

---

Reviewed 6 of 20 files at r10.
Review status: all files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/132#-:-KU7dQfEkZ2sSEg3qHay:bnfp4nl)_

**Pull request merged**
