### PR TITLE
A TESTER - Work/valentin/optim explo plays off

### PR DESCRIPTION
**Pull request by ValentinVERGEZ**
A tester et à discuter.

Après une longue investigation sur les rosout.log de notre match de test, j'en ai fini par remettre en cause le getSidePoints et il semble que le raisonnement de base était légèrement biaisé. Je l'ai corrigé.

J'en ai profité pour mettre ce qui selon moi serait un workaround aux longs déplacements sur machines non vue (détectée par symétrie) qui se foirent (mal placés).

J'ai retiré les nombres d'attentes sur les going visant les côtés des machines.

J'ai mis deux paramètres pour le timeout de la FA, l'un est actuellement utilisé.

---

This change is [Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/111)

### CODE REVIEW

**Comment by vcoelen** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/111)_

**Comment by tdanel** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/111#-:-KLe7Q_1T4pEEVDohu6c:1417088721)_

**Comment by SandraHage** [comment]
Reviewed 7 of 7 files at r1, 3 of 7 files at r2.
Review status: 7 of 11 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/111)_

**Comment by SandraHage** [comment]
Reviewed 1 of 7 files at r2.
Review status: 8 of 11 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/111)_

**Comment by ValentinVERGEZ** [comment]
Testé sur terrain :lgtm_strong: 

---

Review status: 7 of 12 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/111#-:-KLeY1yFv6mROdqOhdkH:1687863575)_

**Pull request merged**
