### PR TITLE
ComputerVision ROI

### PR DESCRIPTION
**Pull request by ValentinVERGEZ**
Première révision, pour servir de base propre à la revue.
Vous pouvez revoir ces modifs, mais c'est essentiellement des suppressions, des changements d'indentations, changement de noms de fichiers, etc
Plus tard il sera plus facile de faire une revue en utilisant la révision 1 comme référence.

---

This change is [Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/68)

### CODE REVIEW

**Comment by vcoelen** [comment]
Reviewed 46 of 49 files at r1.
Review status: 46 of 49 files reviewed at latest revision, 4 unresolved discussions.

---

_[traitement_image/feu_tricolore/include/feu_tricolore/LightDetection.h, line 2 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68#-KJztRLczNAHB9STEn3L:-KJztRLdX5nOHreTCmoV:1310425064) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d61e940db18ad47f3c44debfcd5d5610c3634fbc/traitement_image/feu_tricolore/include/feu_tricolore/LightDetection.h#L2)):_

> ``` objc
> #ifndef _TRAIT_IM__LIGHT_DETECTION__H_
> #define _TRAIT_IM__LIGHT_DETECTION__H_
> ```

_TRAITEMENT_IMAGE__LIGHT_DETECTION__H_

---

_[traitement_image/feu_tricolore/src/display-histogram.cpp, line 15 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68#-KJzuCP-91UDiCUpQ2F5:-KJzuCP-91UDiCUpQ2F6:-1510170524) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d61e940db18ad47f3c44debfcd5d5610c3634fbc/traitement_image/feu_tricolore/src/display-histogram.cpp#L15)):_

> ``` cpp
>   // Initalize histogram arrays
>   for (size_t i = 0; i < hist.size(); i++)
>       hist[i] = Mat::zeros(1, bins, CV_32SC1);
> ```

manque { }

---

_[traitement_image/feu_tricolore/src/LightDetection.cpp, line 14 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68#-KJzwUmw7WViUq3e7_N1:-KJzwUmw7WViUq3e7_N2:1893373801) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d61e940db18ad47f3c44debfcd5d5610c3634fbc/traitement_image/feu_tricolore/src/LightDetection.cpp#L14)):_

> ``` cpp
>   // Ros topics
>   m_image_sub = m_it.subscribe("hardware/camera/platform_camera/image_raw", 1, &LightDetection::imageCb, this);
>   m_nh.setParam("computerVision/lightSignalDetection/image_result/list/0_Flux_origine", "/image_raw");
> ```

Ne doit pas être en dur

---

_[traitement_image/feu_tricolore/src/LightDetection.cpp, line 149 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68#-KJzvbVFp8hcsMzLkO9r:-KJzvbVFp8hcsMzLkO9s:-920299130) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d61e940db18ad47f3c44debfcd5d5610c3634fbc/traitement_image/feu_tricolore/src/LightDetection.cpp#L149)):_

> ``` cpp
> 
>           light.color = light.RED;
>           if(m_nbRedTurnedOn > m_nbImgProcessed*0.66)
> ```

magic number et { }

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68)_

**Comment by tdanel** [comment]
Reviewed 10 of 49 files at r1.
Review status: 47 of 49 files reviewed at latest revision, 8 unresolved discussions.

---

_[traitement_image/feu_tricolore/CMakeLists.txt, line 76 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68#-KK3-8Oo7IbTdu1kNQoM:-KK3-8Oo7IbTdu1kNQoN:-876228890) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d61e940db18ad47f3c44debfcd5d5610c3634fbc/traitement_image/feu_tricolore/CMakeLists.txt#L76)):_

> ``` CMake
> )
> set_target_properties(
>   lecture_feu_node
> ```

en anglais ?

---

_[traitement_image/feu_tricolore/src/lecture_feu_node.cpp, line 7 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68#-KK30Jldb00ZDF4D5JBV:-KK30Jldb00ZDF4D5JBW:-704153682) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d61e940db18ad47f3c44debfcd5d5610c3634fbc/traitement_image/feu_tricolore/src/lecture_feu_node.cpp#L7)):_

> ``` cpp
> {
>     ros::init(argc, argv, "light_detection");
>     LightDetection lf;
> ```

Nom de fichier à mettre en anglais aussi nan ?

---

_[traitement_image/feu_tricolore/src/LightDetection.cpp, line 54 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68#-KK2zQ3iWxt6Q18Lurii:-KK2zQ3iWxt6Q18Lurij:-940385139) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d61e940db18ad47f3c44debfcd5d5610c3634fbc/traitement_image/feu_tricolore/src/LightDetection.cpp#L54)):_

> ``` cpp
>   m_beginOfProcessing = ros::Time::now();
> 
>   m_feedback.percent_complete = (ros::Time::now()-m_beginOfProcessing).toSec() / m_minProcessTimeNeeded;
> ```

Gênant pour ROS si le % est > 100 ?

---

_[traitement_image/feu_tricolore/src/LightDetection.cpp, line 82 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68#-KK2zap1O7RNKi9kWKVb:-KK2zap1O7RNKi9kWKVc:5175079) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d61e940db18ad47f3c44debfcd5d5610c3634fbc/traitement_image/feu_tricolore/src/LightDetection.cpp#L82)):_

> ``` cpp
>   // Quit if inactive action server
>   if (!m_as.isActive())
>         return;
> ```

{}

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68)_

**Comment by ValentinVERGEZ** [comment]
Review status: 47 of 49 files reviewed at latest revision, 8 unresolved discussions.

---

_[traitement_image/feu_tricolore/src/lecture_feu_node.cpp, line 7 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68#-KK30Jldb00ZDF4D5JBV:-KK37RLlSOmlH_NQYGKq:-1521630771) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d61e940db18ad47f3c44debfcd5d5610c3634fbc/traitement_image/feu_tricolore/src/lecture_feu_node.cpp#L7)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> Nom de fichier à mettre en anglais aussi nan ?
> </details>
> Oui, il faudrait. Je ne me sens pas très chaud pour tout bouger pour l'instant. Sachant qu'il faudrait aussi renommer le package pour faire les choses bien.
> C'est rien de très compliqué, mais à si peu de temps de la Robocup, je préfère sincèrement reporter.

Si tu le veux bien, à faire après Leipzig

---

_[traitement_image/feu_tricolore/src/LightDetection.cpp, line 14 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68#-KJzwUmw7WViUq3e7_N1:-KK39sK4oLlt9_koL4TA:1918512794) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d61e940db18ad47f3c44debfcd5d5610c3634fbc/traitement_image/feu_tricolore/src/LightDetection.cpp#L14)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> Ne doit pas être en dur
> </details>
> J'ajoute un TODO pour peut-être paramétrer le topic d'entrée (à moins d'utiliser le remap).
> En complément, j'utilise m_image_sub.getTopic() pour le setParam.

---

_[traitement_image/feu_tricolore/src/LightDetection.cpp, line 54 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68#-KK2zQ3iWxt6Q18Lurii:-KK3AgsSq2Ov-ogzMdoR:-1181837634) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/d61e940db18ad47f3c44debfcd5d5610c3634fbc/traitement_image/feu_tricolore/src/LightDetection.cpp#L54)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> Gênant pour ROS si le % est > 100 ?
> </details>
> Absolument pas, c'est simplement un entier.
> En revanche il manquait une multiplication par 100, je l'ai rajoutée.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68)_

**Comment by tdanel** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68)_

**Comment by tdanel** [comment]
:lgtm:

<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> #### ComputerVision ROI
> 
> Première révision, pour servir de base propre à la revue.
> 
> Vous pouvez revoir ces modifs, mais c'est essentiellement des suppressions, des changements d'indentations, changement de noms de fichiers, etc
> 
> Plus tard il sera plus facile de faire une revue en utilisant la révision 1 comme référence.
> 
> </details>

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/68#-:-KK4MQTmiETs3Mel-kAY:1417088721)_

**Pull request merged**
