### PR TITLE
[Executeur] Clean Up 

### PR DESCRIPTION
**Pull request by tdanel**
Premier jet du nettoyage de l'executeur, j'attend vos remarques

---

This change is [Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/127)

### CODE REVIEW

**Comment by vcoelen** [comment]
Reviewed 31 of 32 files at r1.
Review status: 31 of 32 files reviewed at latest revision, 3 unresolved discussions.

---

_[manager/executeur_taches/include/Machine.h, line 46 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN7w-3f3oPKoAO0S84u:-KN7w-3f3oPKoAO0S84v:2011530640) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/include/Machine.h#L46)):_

> ``` objc
>       std::string m_name;
>       int m_faType;
>     int m_activiType;
> ```

nope!!! :P

---

_[manager/executeur_taches/include/Machine.h, line 70 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN7w83ieS-ZO_mixY1R:-KN7w83ieS-ZO_mixY1S:878576420) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/include/Machine.h#L70)):_

> ``` objc
>       void startFinalAp(int8_t machineType, int8_t machineSide, int8_t machineParameter);
>       int getFaType(){ return m_faType; }
>       int getActiviType(){ return m_activiType; }
> ```

non plus :P

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 136 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN7xYyOvc0BYPWj8SAI:-KN7xYyP55tboYpJPpAp:-1883125723) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/GtServerSrv.cpp#L136)):_

> ``` cpp
>   {
>     case BOTTOM_LEFT:
>     {
> ```

pas nécessaire 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127)_

**Comment by ValentinVERGEZ** [comment]
Globalement c'est pas mal.
Ton indentation Atom doit être réglée sur espace et tabstop à 2. Ok pour les espaces, mais en tabstop 4 stp

Quelques remarques et questions, rien de ouf.

---

Review status: 31 of 32 files reviewed at latest revision, 12 unresolved discussions.

---

_[manager/executeur_taches/include/ArTagClientSrv.h, line 25 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9Lj4TxCrSCLeUfnfa:-KN9Lj4TxCrSCLeUfnfb:-821641325) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/include/ArTagClientSrv.h#L25)):_

> ``` objc
>       virtual  ~ArTagClienSrv();
> 
>     /* Méthodes */
> ```

Tu mets 4 espaces, en dessous y'a deux tabulations.
Soit tu tabules en largeur deux espaces (pas bon), soit t'as pas aligné le commentaire.

---

_[manager/executeur_taches/include/LocaSubscriber.h, line 38 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9N9PYvRwjRhFN4NeF:-KN9N9PYvRwjRhFN4NeG:-471516127) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/include/LocaSubscriber.h#L38)):_

> public:
>   /\* Constructeur _/
>   LocaSubscriber();
>  
>   /_ Destructeur _/
>   virtual  ~LocaSubscriber();
>  
>   /_ Méthodes */
>   void machinesCallback(const deplacement_msg::MachinesConstPtr &msg);
>   void spin();
>  
>   std::vector<MPS> machines(){return m_machines;};
>   bool haveAllTheMachines(){return m_explo_completed;};
>  
> private:
>   ros::Subscriber m_sub;
>   std::vector<MPS> m_machines;
>   b
> Indente en tabstop 4

---

_[manager/executeur_taches/include/Machine.h, line 46 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN7w-3f3oPKoAO0S84u:-KN9NIEgoFLBQ1GRLDSO:-510466975) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/include/Machine.h#L46)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> nope!!! :P
> </details>
> :+1: 

---

_[manager/executeur_taches/include/Machine.h, line 70 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN7w83ieS-ZO_mixY1R:-KN9NLDN2UR5qjMneCw8:-510466975) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/include/Machine.h#L70)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> non plus :P
> </details>
> :+1: 

---

_[manager/executeur_taches/include/MyElements.h, line 48 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9NXDvtthGEo7R5qtI:-KN9NXDvtthGEo7R5qtJ:1751698849) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/include/MyElements.h#L48)):_

> ``` objc
>       RingStation& getRS1();
>       RingStation& getRS2();
>       RingStation& getRS(int color);
> ```

Pas color, num machine (pareil en dessous avec getCS()).

On a que deux RS, deux fonctions c'était pas la mort. Personnellement je préfère.
Tu peux parfaitement faire getRS(int numMahine) ET getRS1() getRS2().

La première fonction peut-être utile pour switcher de l'une à l'autre sans se soucier de laquelle on a et les deux autres par commodité comme l'est la fonction isDS() sur la classe Machine.

---

_[manager/executeur_taches/src/BaseStation.cpp, line 66 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9ObB3CSzD_W2XIVUZ:-KN9ObB3CSzD_W2XIVU_:-1715295909) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/c5bc08857c74de0c4e2b6cab87f4778bd52b9d73/manager/executeur_taches/src/BaseStation.cpp#L66)):_

> ``` cpp
>   this->startFinalAp(FinalApproachingGoal::BS, FinalApproachingGoal::OUT, FinalApproachingGoal::CONVEYOR);
>   this->take();
>   msg = msgToGT(n_robot,activity::END,activity::BS,n_order); 
> ```

J'ai pas encore vu les msgToGT dans l’exécuteur. On les gère ?

Si ça casse pas la fonctionnalité du GT, ça peut attendre la refonte. 

---

_[manager/executeur_taches/src/CapStation.cpp, line 24 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9P-72L0L0Ct5PihJr:-KN9P-72L0L0Ct5PihJs:677641835) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/CapStation.cpp#L24)):_

> ``` cpp
>   m_name += std::to_string(nb);
>   if (nb == 1)  m_activiType = activity::CS1;
>   if (nb == 2)  m_activiType = activity::CS2;
> ```

Un assert pour le cas du nb non géré. nb peut être unsigned
Vu que tu assert, l'affectation peut-être faite par un simple ternaire. A la limite if puis else.

---

_[manager/executeur_taches/src/FinalApproachingClient.cpp, line 42 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9PlgL9wHnHqEPO9mq:-KN9PlgL9wHnHqEPO9mr:2069301535) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/FinalApproachingClient.cpp#L42)):_

>   actionlib::SimpleActionClient<final_approach_msg::FinalApproachingAction> client("navigation/FinalApproach",true);
>  
>   ROS_INFO("Waiting for fa action Server to start");
>  
>   client.waitForServer();
>  
>   ROS_INFO("Action server started, sending goal");
>  
>   final_approach_msg::FinalApproachingGoal goal;
>   goal.type = machineType;
>   goal.side = machineSide;
>   goal.parameter = machineParameter;
>   client.sendGoal(goal);
>  
>   //wait for the action to return
>   bool finished_before_timeout = client.waitForResult(ros::Duration(m_globalTimeout()));
>  
>   if(finished_before_timeout)
>   {
>     actionlib::SimpleClientGoalState state = client.getState();
>     m_success = client.getResult()->success;
>     ROS_INFO("Action finished : %s ",state.toString().c_str());
>  
>   }
>   else
>   {
>     ROS_WARN("FinalApproach aborted due to timeout. Will continue");
>     client.cancelGoal();
>     m_success = true;
>   }
> Indentation, pas deux espaces mais quatre

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 136 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN7xYyOvc0BYPWj8SAI:-KN9RVMBfToynmDo_eth:307534604) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/GtServerSrv.cpp#L136)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> pas nécessaire 
> </details>
> :+1: 
> Et moins lisible

---

_[manager/executeur_taches/src/Machine.cpp, line 109 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9Q58IgiifA1lC0Uuh:-KN9Q58IgiifA1lC0Uui:1427978477) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/Machine.cpp#L109)):_

> bool Machine::isDS(int id)
> {
>   if(id == C_DS_IN || id == C_DS_OUT || id == M_DS_IN || id == M_DS_OUT)
>   {
>     return true;
>   }
>   return false;
> }

Remplace par :

> bool Machine::isDS()
> {
>     return false; // Avec la bonne indentation c'est mieux :-D
> } 

Et surcharge la fonction dans la classe DeliveryStation.

Si tu penses que tu dois travailler sur un ArTag alors ok pour ajouter une fonction isDSfromId, mais dans les common sur les ArTag alors.
(Je t'autorises à trouver un meilleur nom de fonction :kissing_heart: )

---

_[manager/executeur_taches/src/MyElements.cpp, line 57 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9Qsfli_wYAKC4PvY9:-KN9Qsfli_wYAKC4PvYA:-403549738) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/MyElements.cpp#L57)):_

> RingStation& MyElements::getRS(int color)
> {
>   //TODO: setter les couleurs de RING (pas fait !)
>   switch (color)
>   {
> <details><summary>
> 
> <i alt="summary">Quoted 19 lines of code…</i></summary>
> 
> 
>     case orderRequest::GREEN :
>       if     (m_rs1.getGreenRing() != 0)  return m_rs1;
>       else if(m_rs2.getGreenRing() != 0)  return m_rs2;
>     break;
>     case orderRequest::YELLOW :
>       if     (m_rs1.getYellowRing() != 0) return m_rs1;
>       else if(m_rs2.getYellowRing() != 0) return m_rs2;
>     break;
>     case orderRequest::BLUE :
>       if     (m_rs1.getBlueRing() != 0)   return m_rs1;
>       else if(m_rs2.getBlueRing() != 0)   return m_rs2;
>     break;
>     case orderRequest::ORANGE :
>       if     (m_rs1.getOrangeRing() != 0) return m_rs1;
>       else if(m_rs2.getOrangeRing() != 0) return m_rs2;
>     break;
>     default :
>       //TODO: TBD
>     break;
> </details>
>   }
> }

Ok, my bad pour la remarque de tout à l'heure. Tu peux m'éclairer sur ce qu'il faut faire avec la couleur de l'équipe et les ring ?

---

_[manager/executeur_taches/src/MyElements.cpp, line 82 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9R3feS7r82IF7tUvS:-KN9R3feS7r82IF7tUvT:1680651530) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/MyElements.cpp#L82)):_

> n& MyElements::getCS(int color)
> {
>   //TODO: setter les couleurs de CAP (pas fait !)
>   switch (color)
>   {
> <details><summary>
> 
> <i alt="summary">Quoted 11 lines of code…</i></summary>
> 
> 
>     case orderRequest::GREY :
>       if     (m_cs1.getGreyCap() != 0)  return m_cs1;
>       else if(m_cs1.getGreyCap() != 0)  return m_cs2;
>     break;
>     case orderRequest::BLACK :
>       if     (m_cs1.getBlackCap() != 0) return m_cs1;
>       else if(m_cs2.getBlackCap() != 0) return m_cs2;
>     break;
>     default :
>       //TODO: TBD
>     break;
> </details>
>   }
> }

Même question que pour RS

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-:-KN9RvFiFm-zF3sLZDD8:-2008723428)_

**Comment by tdanel** [comment]
Review status: 31 of 32 files reviewed at latest revision, 13 unresolved discussions.

---

_[manager/executeur_taches/include/ArTagClientSrv.h, line 23 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KNB_WeSPpvDep1ewqMX:-KNB_WeSPpvDep1ewqMY:676378373) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/include/ArTagClientSrv.h#L23)):_

> ,

---

_[manager/executeur_taches/include/MyElements.h, line 48 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9NXDvtthGEo7R5qtI:-KNB_lCuA20lH6MDiMBe:-792028519) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/include/MyElements.h#L48)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> Pas color, num machine (pareil en dessous avec getCS()).
> 
> On a que deux RS, deux fonctions c'était pas la mort. Personnellement je préfère.
> Tu peux parfaitement faire getRS(int numMahine) ET getRS1() getRS2().
> 
> La première fonction peut-être utile pour switcher de l'une à l'autre sans se soucier de laquelle on a et les deux autres par commodité comme l'est la fonction isDS() sur la classe Machine.
> </details>
> Color de cap ;)

---

_[manager/executeur_taches/src/BaseStation.cpp, line 66 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9ObB3CSzD_W2XIVUZ:-KNB_oZc3DdCBIE27IQI:-2030412223) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/c5bc08857c74de0c4e2b6cab87f4778bd52b9d73/manager/executeur_taches/src/BaseStation.cpp#L66)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> J'ai pas encore vu les msgToGT dans l’exécuteur. On les gère ?
> 
> Si ça casse pas la fonctionnalité du GT, ça peut attendre la refonte. 
> </details>
> Avant le responseToGT dans GtServerSrv.cpp

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 136 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN7xYyOvc0BYPWj8SAI:-KNBa21I2EQXBbfzI5Fu:-100376865) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/GtServerSrv.cpp#L136)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> :+1: 
> Et moins lisible
> </details>
> la flemme, moins lisible non ^^

---

_[manager/executeur_taches/src/Machine.cpp, line 109 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9Q58IgiifA1lC0Uuh:-KNBaHH0pnbGGntAKVxM:-1208318016) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/Machine.cpp#L109)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> > bool Machine::isDS(int id)
> > {
> >   if(id == C_DS_IN || id == C_DS_OUT || id == M_DS_IN || id == M_DS_OUT)
> >   {
> >     return true;
> >   }
> >   return false;
> > }
> 
> Remplace par :
> 
> > bool Machine::isDS()
> > {
> >     return false; // Avec la bonne indentation c'est mieux :-D
> > } 
> 
> Et surcharge la fonction dans la classe DeliveryStation.
> 
> Si tu penses que tu dois travailler sur un ArTag alors ok pour ajouter une fonction isDSfromId, mais dans les common sur les ArTag alors.
> (Je t'autorises à trouver un meilleur nom de fonction :kissing_heart: )
> </details>
> En fait non, c'est dans la partie exploration de l'executeur, on déclare une Machine, et on travaille dessus, on n'a pas encore les classes filles ^^ c'est logique d'ailleurs, pourquoi demander à une DS si c'est une DS ? ;)

---

_[manager/executeur_taches/src/MyElements.cpp, line 57 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9Qsfli_wYAKC4PvY9:-KNBadTO3O3U945HBXXY:321676009) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/MyElements.cpp#L57)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> > RingStation& MyElements::getRS(int color)
> > {
> >   //TODO: setter les couleurs de RING (pas fait !)
> >   switch (color)
> >   {
> >     case orderRequest::GREEN :
> >       if     (m_rs1.getGreenRing() != 0)  return m_rs1;
> >       else if(m_rs2.getGreenRing() != 0)  return m_rs2;
> >     break;
> >     case orderRequest::YELLOW :
> >       if     (m_rs1.getYellowRing() != 0) return m_rs1;
> >       else if(m_rs2.getYellowRing() != 0) return m_rs2;
> >     break;
> >     case orderRequest::BLUE :
> >       if     (m_rs1.getBlueRing() != 0)   return m_rs1;
> >       else if(m_rs2.getBlueRing() != 0)   return m_rs2;
> >     break;
> >     case orderRequest::ORANGE :
> >       if     (m_rs1.getOrangeRing() != 0) return m_rs1;
> >       else if(m_rs2.getOrangeRing() != 0) return m_rs2;
> >     break;
> >     default :
> >       //TODO: TBD
> >     break;
> >   }
> > }
> 
> Ok, my bad pour la remarque de tout à l'heure. Tu peux m'éclairer sur ce qu'il faut faire avec la couleur de l'équipe et les ring ?
> </details>
> ringColor, pas teamColor :)

---

_[manager/executeur_taches/src/MyElements.cpp, line 82 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9R3feS7r82IF7tUvS:-KNBaiqmjFpTH3JoJeZL:-1831186447) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/MyElements.cpp#L82)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> > n& MyElements::getCS(int color)
> > {
> >   //TODO: setter les couleurs de CAP (pas fait !)
> >   switch (color)
> >   {
> >     case orderRequest::GREY :
> >       if     (m_cs1.getGreyCap() != 0)  return m_cs1;
> >       else if(m_cs1.getGreyCap() != 0)  return m_cs2;
> >     break;
> >     case orderRequest::BLACK :
> >       if     (m_cs1.getBlackCap() != 0) return m_cs1;
> >       else if(m_cs2.getBlackCap() != 0) return m_cs2;
> >     break;
> >     default :
> >       //TODO: TBD
> >     break;
> >   }
> > }
> 
> Même question que pour RS
> </details>
> capColor, pas teamColor :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127)_

**Comment by tdanel** [comment]
Review status: 31 of 32 files reviewed at latest revision, 13 unresolved discussions.

---

_[manager/executeur_taches/src/CapStation.cpp, line 24 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9P-72L0L0Ct5PihJr:-KNBckup2CfoiL8Ib28M:1760588077) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/CapStation.cpp#L24)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> Un assert pour le cas du nb non géré. nb peut être unsigned
> Vu que tu assert, l'affectation peut-être faite par un simple ternaire. A la limite if puis else.
> </details>
> ternaire sur enum pas possible apparemment ^^

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127)_

**Comment by ValentinVERGEZ** [comment]
Quelques remarques sont bloquantes.
A ces remarques près, c'est bientôt mergeable.

---

Reviewed 34 of 37 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

_[manager/executeur_taches/include/ArTagClientSrv.h, line 23 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KNB_WeSPpvDep1ewqMX:-KNDr9SgJCC2dv9lmxEs:-1749260511) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/include/ArTagClientSrv.h#L23)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> > ,
> > </details>
> > :question: 

---

_[manager/executeur_taches/include/ArTagClientSrv.h, line 8 [r3]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KNDqaSVJdK9D3INxp4Q:-KNDqaSVJdK9D3INxp4R:1566663963) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4f1798f466d2d7edd41245aa9d29f38b304dbd84/manager/executeur_taches/include/ArTagClientSrv.h#L8)):_

> /**
> - \file       ArTagClientSrv.h
> - \class      ArTagClientSrv
> - \brief      classe client service ArTag
> - \author     Hage Chehade Sandra (sandra.hage-chehade@polytech-lille.net)
> - \date       2015-10-10
> - \copyright   2016, Association de Robotique de Polytech Lille All rights reserved
>   */

Pourquoi retirer les espaces ? Est-ce c'est un outils qui t'as fait ça automatiquement ? Si oui, c'est la première fois que je vois ce format. Le format précédent, c'était un format standard.

PS: Si tu l'as fait à la main, c'est inquiétant :stuck_out_tongue_closed_eyes: 

---

_[manager/executeur_taches/include/Machine.h, line 55 [r3]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KNE-uzjZXnNzHMDb5IF:-KNE-uzjZXnNzHMDb5IG:-47034312) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/c5bc08857c74de0c4e2b6cab87f4778bd52b9d73/manager/executeur_taches/include/Machine.h#L55)):_

> virtual void FonctionVirtuelle() = 0;
>  

Pourquoi tu l'enlèves ?
Ça fait écho à un autre commentaire sur l'héritage des classes RingStation/BaseStation & co, on n'instancie pas de Machine, c'est une classe abstraite. 

---

_[manager/executeur_taches/src/CapStation.cpp, line 24 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9P-72L0L0Ct5PihJr:-KNDscI8n9chtz7tDLpX:420701978) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/CapStation.cpp#L24)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> ternaire sur enum pas possible apparemment ^^
> </details>
> Ça m'étonne, mais le if else me va

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 136 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN7xYyOvc0BYPWj8SAI:-KNDsvVjAt7-_1GLQ1xi:-2012457601) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/GtServerSrv.cpp#L136)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> la flemme, moins lisible non ^^
> </details>
> :trollface: 

---

_[manager/executeur_taches/src/Machine.cpp, line 109 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9Q58IgiifA1lC0Uuh:-KN9Q1iLTtsYdKHWR_BQ:1434040966) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/Machine.cpp#L109)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> En fait non, c'est dans la partie exploration de l'executeur, on déclare une Machine, et on travaille dessus, on n'a pas encore les classes filles ^^ c'est logique d'ailleurs, pourquoi demander à une DS si c'est une DS ? ;)
> </details>
> Et bien parce qu'on travaille sur un pointeur de machine, pointant en réalité sur une instance d'une CS/RS/BS/DS. La seule façon de connaître le type de la machine pointée c'est effectivement de lui demander.
> Mais le type est bien connu, on ne travaille pas sur une instance de Machine. :relieved: 

D'ailleurs la classe Machine, si elle ne l'est pas déjà, devrait être virtuelle non ?

---

_[manager/executeur_taches/src/MyElements.cpp, line 57 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9Qsfli_wYAKC4PvY9:-KNDyWo2whTohMCk14P7:1214746523) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/MyElements.cpp#L57)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> ringColor, pas teamColor :)
> </details>
> Ok, c'est orienté production. Tu veux obtenir la machine RS qui fait elle couleur de ring. C'était pas clair pour moi.

m_greenRing and co représente le fait que la machine sait les fournir ou le nombre qu'elle contient ?
Si c'est le simple fait, faudra changer en bool.
Si c'est un nombre, ça devient dangereux, tu peux retourner la mauvaise machine juste parce que la bonne machine est à sec de ring.

Mais bon, on sort du cadre du cleanup.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-:-KNE0f6f6iYVGd4L0IdG:552302701)_

**Comment by tdanel** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_[manager/executeur_taches/include/ArTagClientSrv.h, line 8 [r3]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KNDqaSVJdK9D3INxp4Q:-KNGUrywAUwVXcOJqE1E:-996712887) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/4f1798f466d2d7edd41245aa9d29f38b304dbd84/manager/executeur_taches/include/ArTagClientSrv.h#L8)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> > /**
> > - \file         ArTagClientSrv.h
> > - \class        ArTagClientSrv
> > - \brief        classe client service ArTag
> > - \author       Hage Chehade Sandra (sandra.hage-chehade@polytech-lille.net)
> > - \date     2015-10-10
> > - \copyright   2016, Association de Robotique de Polytech Lille All rights reserved
> >   */
> 
> Pourquoi retirer les espaces ? Est-ce c'est un outils qui t'as fait ça automatiquement ? Si oui, c'est la première fois que je vois ce format. Le format précédent, c'était un format standard.
> 
> PS: Si tu l'as fait à la main, c'est inquiétant :stuck_out_tongue_closed_eyes: 
> </details>
> Auto indent sur atom

---

_[manager/executeur_taches/src/Machine.cpp, line 109 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9Q58IgiifA1lC0Uuh:-KNGVQROJt_td60NjwPf:107948271) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/Machine.cpp#L109)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> Et bien parce qu'on travaille sur un pointeur de machine, pointant en réalité sur une instance d'une CS/RS/BS/DS. La seule façon de connaître le type de la machine pointée c'est effectivement de lui demander.
> Mais le type est bien connu, on ne travaille pas sur une instance de Machine. :relieved: 
> 
> D'ailleurs la classe Machine, si elle ne l'est pas déjà, devrait être virtuelle non ?
> </details>
> Pardon, pardon, au temps pour moi ;)

---

_[manager/executeur_taches/src/MyElements.cpp, line 57 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9Qsfli_wYAKC4PvY9:-KNGVuCPvul72UwIOtMv:-591098571) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/MyElements.cpp#L57)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> Ok, c'est orienté production. Tu veux obtenir la machine RS qui fait elle couleur de ring. C'était pas clair pour moi.
> 
> m_greenRing and co représente le fait que la machine sait les fournir ou le nombre qu'elle contient ?
> Si c'est le simple fait, faudra changer en bool.
> Si c'est un nombre, ça devient dangereux, tu peux retourner la mauvaise machine juste parce que la bonne machine est à sec de ring.
> 
> Mais bon, on sort du cadre du cleanup.
> </details>
> je pense que c'est le simple fait d'avoir la couleur :) faudra voir ça oui :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127)_

**Comment by tdanel** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_[manager/executeur_taches/src/Machine.cpp, line 109 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127#-KN9Q58IgiifA1lC0Uuh:-KNGapDdRqb0LOT8i0Ab:-1783479759) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/fef90af76f3ed13efcfcfcc3d68c574793f5e8b1/manager/executeur_taches/src/Machine.cpp#L109)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> Pardon, pardon, au temps pour moi ;)
> </details>
> En fait ya un soucis avec ça... on ne récupère que l'instance à la ligne 592 donc toutes les machines avant sont des nullptr :( c'est pareil pour machineSideId qui est demandé à la ligne 582 mais est utilisé avant... (= 0)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/127)_

**Comment by ValentinVERGEZ** [comment]
Ok, c'est tout bon pour moi.
Je ne peux pas accéder à reviewable, c'est embêtant pour le :lgtm:

**Pull request merged**
