### PR TITLE
Work/sandra/update exec

### PR DESCRIPTION
**Pull request by tdanel**
A ne pas deleter

---

This change is [Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/72)

### CODE REVIEW

**Comment by vcoelen** [comment]
Reviewed 3 of 6 files at r1, 20 of 26 files at r2.
Review status: 23 of 28 files reviewed at latest revision, 6 unresolved discussions.

---

_[manager/executeur_taches/include/CapStation.h, line 31 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72#-KK2zBZqb7L8642dCZF-:-KK2zBZqb7L8642dCZF0:995006277) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/834584f10f20c2ac48c905685c12c8663641acb2/manager/executeur_taches/include/CapStation.h#L31)):_

> ``` objc
>       /* Constructeur */
>       CapStation(int teamColor);
>       CapStation(int nb, int teamColor);
> ```

teamColor avant nb pour pinailler

---

_[manager/executeur_taches/include/RingStation.h, line 31 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72#-KK2zyn7ZllUWvN8Cu5r:-KK2zyn7ZllUWvN8Cu5s:-2033803204) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/834584f10f20c2ac48c905685c12c8663641acb2/manager/executeur_taches/include/RingStation.h#L31)):_

> ``` objc
>   /* Constructeur */
>   RingStation(int teamColor);
>   RingStation(int nb, int teamColor);
> ```

idem ordre

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 130 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72#-KK3-JD2DjFF6IOlaRXV:-KK3-JD2DjFF6IOlaRXW:1090279228) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/834584f10f20c2ac48c905685c12c8663641acb2/manager/executeur_taches/src/GtServerSrv.cpp#L130)):_

> ``` cpp
> }
> 
> void GtServerSrv::interpretationZone()
> ```

A supprimer ?

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 586 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72#-KK30bJI6mfLE_ZtlJ8S:-KK30bJJjjQ1LCj5qowx:1612180052) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/834584f10f20c2ac48c905685c12c8663641acb2/manager/executeur_taches/src/GtServerSrv.cpp#L586)):_

> ``` cpp
> 
>               // Reporter machine
>               reportClient.reporting(machine->getName(), m_ei->type, req.id);
> ```

Normalement à la fin de l'explo de la machine on connaît la position input et output de la machine que l'on peut stocker dans les champs prévus à cet effet dans la classe machine. Ça pourrait bien de les stocker ici pour utilisation future (production)

---

_[manager/executeur_taches/src/MyElements.cpp, line 116 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72#-KK31A86_Q1bLu9SNhUP:-KK31A86_Q1bLu9SNhUQ:147674978) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/834584f10f20c2ac48c905685c12c8663641acb2/manager/executeur_taches/src/MyElements.cpp#L116)):_

> ``` cpp
> 
>   ROS_ERROR("Invalid ArTagID for this team/color: %d (teamcolor: %d)", arTag, teamColor);
>   return NULL;
> ```

nullptr

---

_[simulation/gazebo_sim_launch/others/overview.rviz, line 668 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72#-KK31YfGbfICLenOtws0:-KK31YfGbfICLenOtws1:-1895195147) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/834584f10f20c2ac48c905685c12c8663641acb2/simulation/gazebo_sim_launch/others/overview.rviz#L668)):_

> ``` YAML
>       Namespaces:
>         {}
> <<<<<<< HEAD
> ```

Attention un merge a échoué ici 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72)_

**Comment by ValentinVERGEZ** [comment]
Je n'ai regardé qu'un fichier, je laisse le reste de la revue à Sandra et Vincent

<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> #### Work/sandra/update exec
> 
> A ne pas deleter
> 
> </details>

---

Review status: 20 of 31 files reviewed at latest revision, 7 unresolved discussions.

---

_[manager/executeur_taches/src/MyElements.cpp, line 9 [r3]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72#-KK3SfCNOM7mbC0VESZv:-KK3SfCOrmIAE2jGVb-c:-111868402) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/1aa72c4698c69d58267108b4be80afb4a5a440e3/manager/executeur_taches/src/MyElements.cpp#L9)):_

> ``` cpp
> , m_rs2(2, teamColor)
> , m_cs1(1, teamColor)
> , m_cs2(2, teamColor)
> ```

Attention, ordre des paramètres

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72#-:-KK3TDUNyAA88UjTPkEC:1921041667)_

**Comment by vcoelen** [comment]
Reviewed 9 of 11 files at r3.
Review status: 29 of 31 files reviewed at latest revision, 7 unresolved discussions.

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 586 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72#-KK30bJI6mfLE_ZtlJ8S:-KK3buLzUcKSUGIw9ez8:2007956403) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/834584f10f20c2ac48c905685c12c8663641acb2/manager/executeur_taches/src/GtServerSrv.cpp#L586)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> Normalement à la fin de l'explo de la machine on connaît la position input et output de la machine que l'on peut stocker dans les champs prévus à cet effet dans la classe machine. Ça pourrait bien de les stocker ici pour utilisation future (production)
> </details>
> Si tu le fais pas, est-ce que tu peux mettre une issue ou un TODO?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72)_

**Comment by tdanel** [comment]
Review status: 29 of 31 files reviewed at latest revision, 7 unresolved discussions.

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 586 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72#-KK30bJI6mfLE_ZtlJ8S:-KK3d7LtiMgbLGesOOla:-443371371) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/834584f10f20c2ac48c905685c12c8663641acb2/manager/executeur_taches/src/GtServerSrv.cpp#L586)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> Si tu le fais pas, est-ce que tu peux mettre une issue ou un TODO?
> </details>
> Je m'en occupe cet aprem

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72)_

**Comment by vcoelen** [comment]
:lgtm:

<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> Je n'ai regardé qu'un fichier, je laisse le reste de la revue à Sandra et Vincent
> </details>

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[manager/executeur_taches/src/GtServerSrv.cpp, line 586 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72#-KK30bJI6mfLE_ZtlJ8S:-KK3dbDr6sgAsoZvB_zA:-669342073) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/834584f10f20c2ac48c905685c12c8663641acb2/manager/executeur_taches/src/GtServerSrv.cpp#L586)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> Je m'en occupe cet aprem
> </details>
> D'accord. C'est pas bloquant pour moi, s'il n'y a rien d'autre je passe la PR.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/72#-:-KK3dqtsFKIHbntbiIk8:1417088721)_

**Pull request merged**
