### PR TITLE
Work/thomas/recalage

### PR DESCRIPTION
**Pull request by tdanel**
This change is [Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/115)

### CODE REVIEW

**Comment by ValentinVERGEZ** [comment]
Je dois encore relire plus attentivement le code du nœud principal.

Est-ce que c'était soumis rapidement pour le match ou c'est déjà intégrable en devel ?

---

Reviewed 7 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

_[common/geometry_utils/include/geometry_utils/geometry_utils.h, line 134 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/115#-KMKuTv4KUAOXQ3SVZpE:-KMKuTv4KUAOXQ3SVZpF:-1563795225) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/7bbfcd0d02ab911783d5faf302dd5fb051e0d77e/common/geometry_utils/include/geometry_utils/geometry_utils.h#L134)):_

> ``` objc
> }
> 
> inline double normalizeAngle(const double &angle, double lowLimit = -M_PI, double highLimit = M_PI)
> ```

Pourquoi passer un double par référence pour ensuite ne pas le modifier ?
Laisse le en copie.
Le fait de devoir créer une variable temporaire ensuite, avec affectation par copie est presque (si ce n'est plus) consommateur.

Pour lowLimit et highLimit si tu veux, passe encore, tu économiseras réellement une copie. Mais pour un double perso je m'en fout de la copie.

---

_[navigation/localisation/CMakeLists.txt, line 179 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/115#-KMKwQU57qUHcb-3b0pn:-KMKwQU57qUHcb-3b0po:677491219) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/7bbfcd0d02ab911783d5faf302dd5fb051e0d77e/navigation/localisation/CMakeLists.txt#L179)):_

> ``` CMake
>   src/recalage_node.cpp
>   src/LaserScan.cpp)
> set_target_properties(recalage PROPERTIES COMPILE_FLAGS -std=c++0x)
> ```

c++1

---

_[navigation/localisation/include/localisation/LaserScan.h, line 29 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/115#-KMKwYqjODvAZh5Dhyww:-KMKwYqkrYCYmkOwTzqz:-742914520) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/7bbfcd0d02ab911783d5faf302dd5fb051e0d77e/navigation/localisation/include/localisation/LaserScan.h#L29)):_

> ``` objc
> 
>   const std::vector<float>& getRanges() const;
>   const std::vector<geometry_msgs::Point>& getPointVector() const;
> ```

A moins d'un bug d'affichage, tu indentes avec deux espaces, c'est chiant.

---

_[navigation/localisation/launch/recalage.launch, line 7 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/115#-KMKxT4L_i5LZEswJaTo:-KMKxT4L_i5LZEswJaTp:1769218803) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/7bbfcd0d02ab911783d5faf302dd5fb051e0d77e/navigation/localisation/launch/recalage.launch#L7)):_

> ``` XML
>   <group ns="robotino1">
>     <param name="teamColor" value="magenta" />
>     <param name="robotNamespace" value="robotino1/" />
> ```

C'est pour tf ? 
A uniformiser plus tard dans tous notre code pour utiliser plutôt un param tf_prefix.

Il me semble qu'actuellement on utilise simRobotNamespace, à tort (mea culpa)

---

_[navigation/localisation/src/recalage_node.cpp, line 10 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/115#-KMKxDSuNIbkpDXGQNpc:-KMKxDSuNIbkpDXGQNpd:954623679) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/7bbfcd0d02ab911783d5faf302dd5fb051e0d77e/navigation/localisation/src/recalage_node.cpp#L10)):_

> ``` cpp
> std::string g_ns;
> tf::TransformListener *g_tf_listener;
> int counter;
> ```

g_counter

---

_[navigation/localisation/src/recalage_node.cpp, line 11 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/115#-KMKxFk8qDEzjfUzQjgp:-KMKxFk8qDEzjfUzQjgq:1331695115) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/7bbfcd0d02ab911783d5faf302dd5fb051e0d77e/navigation/localisation/src/recalage_node.cpp#L11)):_

> ``` cpp
> tf::TransformListener *g_tf_listener;
> int counter;
> robotino_msgs::ResetOdometry setpoint;
> ```

g_setpoint

---

_[navigation/localisation/src/recalage_node.cpp, line 127 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/115#-KMKwtpfBLYHer6YxNdJ:-KMKwtpfBLYHer6YxNdK:2115596863) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/7bbfcd0d02ab911783d5faf302dd5fb051e0d77e/navigation/localisation/src/recalage_node.cpp#L127)):_

> ``` cpp
>     //Initialisation du noeud ROS
>     ros::init(argc, argv, "recalage");
>     ROS_INFO("Starting node recalage_node");
> ```

Tu peux récupérer le nom du nœud plutôt que de l'écrire en dur (cas où renommer dans un launchfile par exemple).
Puis ton nom en dur est différent de celui de ton init :smile: 

---

_[navigation/localisation/src/recalage_node.cpp, line 156 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/115#-KML-CtdbUG1DKGJrtGf:-KML-CtepjfHziaVnUUj:-1597529184) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/7bbfcd0d02ab911783d5faf302dd5fb051e0d77e/navigation/localisation/src/recalage_node.cpp#L156)):_

> ``` cpp
>     while(n.ok() && counter < 10)
>     {
>       robotino_msgs::ResetOdometry resetPosition = gimmePositionBiatch(laserData);
> ```

Ahem :smile: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/115#-:-KML-sDvFQhEFQr9ZDjl:-653648835)_

**Comment by tdanel** [comment]
C'est loin d'être intégrable ;) Beaucoup de trucs à revoir, à laisser pour correction

---

Review status: 7 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/115#-:-KMNlfRjfjtAD6LB9J1l:-594465336)_

**Comment by vcoelen** [comment]
Review status: 7 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

_[common/geometry_utils/include/geometry_utils/geometry_utils.h, line 134 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/115#-KMKuTv4KUAOXQ3SVZpE:-KMQknqSC-kPH94nBBUp:-1559428061) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/7bbfcd0d02ab911783d5faf302dd5fb051e0d77e/common/geometry_utils/include/geometry_utils/geometry_utils.h#L134)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> Pourquoi passer un double par référence pour ensuite ne pas le modifier ?
> Laisse le en copie.
> Le fait de devoir créer une variable temporaire ensuite, avec affectation par copie est presque (si ce n'est plus) consommateur.
> 
> Pour lowLimit et highLimit si tu veux, passe encore, tu économiseras réellement une copie. Mais pour un double perso je m'en fout de la copie.
> </details>
> Au contraire c'est plutôt propre comme code forcer explicitement la création d'une variable temporaire grâce à une référence constante. Ça évite des problème d’ambiguïté ou de portée, lorsqu'on a tendance à utiliser des paramètres de fonctions comme des variables locales ce qui n'est pas une bonne pratique, là le compilateur va t'en empêcher c'est une bonne chose. 
> Pour lowLimit et highLimit, oui, mais je ne sais pas si c'est possible avec les valeur par défauts. 
> Oui, on s'en fout de la copie, mais on ne se fout pas forcément de l'endroit ou elle est faite. 

---

_[navigation/localisation/CMakeLists.txt, line 179 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/115#-KMKwQU57qUHcb-3b0pn:-KMQmCo40_28rHHOY7nK:-581224904) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/7bbfcd0d02ab911783d5faf302dd5fb051e0d77e/navigation/localisation/CMakeLists.txt#L179)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> c++1
> </details>
> c++11 :P

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/115)_

**Comment by tdanel** [comment]
A revoir / refaire
Fera partie de la procédure d'initialisation

**Pull request closed without merging**
