### PR TITLE
Work/thomas/localisation

### PR DESCRIPTION
**Pull request by tdanel**
This change is [Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/64)

### CODE REVIEW

**Comment by tdanel** [comment]
Pull request pour correction du path tracker python + détection des murs et machines
Ne pas delete la branche, je travaille encore sur la localisation

**Comment by ValentinVERGEZ** [comment]
Dans l'ensemble c'est pas mal, c'est même plutôt sympa.
J'ai fait quelques remarques, certaines bloquantes, certains qui ne concernait pas directement ton code (oui sorry :neutral_face: ) et la revue n'est pas exhaustive. 

Du coup je repasserai sur la revue ou laisserai Vincent la compléter.

<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> Pull request pour correction du path tracker python + détection des murs et machines
> 
> Ne pas delete la branche, je travaille encore sur la localisation
> </details>

---

Reviewed 18 of 22 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

_[navigation/grid_maker/src/grid_maker_node.cpp, line 50 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgBgvjB86LXFGozxC3:-KJgBgvjB86LXFGozxC4:364737189) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/navigation/grid_maker/src/grid_maker_node.cpp#L50)):_

> ``` cpp
>     ros::NodeHandle nh;
>     std::string tf_prefix;
>     nh.param<std::string>("simuRobotNamespace", tf_prefix, "");;
> ```

Un point virgule de trop (sûrement pareil là où t'as fait le copier/coller)

---

_[navigation/grid_maker/src/grid_maker_node.cpp, line 88 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgCH_c7EaHX1ywZYBv:-KJgCH_c7EaHX1ywZYBw:589412238) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/navigation/grid_maker/src/grid_maker_node.cpp#L88)):_

> ``` cpp
>     nh.param<double>("field/resolution", resolution, 0.05);
> 
>     std::string frame_id = tf_prefix+"map";
> ```

Attention, frame_id est modifié ensuite

---

_[navigation/grid_maker/src/grid_maker_node.cpp, line 89 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgC0vJ6F9FOBk6g57T:-KJgC0vJ6F9FOBk6g57U:-1230640600) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/navigation/grid_maker/src/grid_maker_node.cpp#L89)):_

> ``` cpp
> 
>     std::string frame_id = tf_prefix+"map";
>     std::cout << "FRAME ID = " << frame_id << std::endl;
> ```

A virer ou remplacer par du ROS_LOG

---

_[navigation/grid_maker/src/grid_maker_node.cpp, line 181 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgCWqBs7Jql_LotUMB:-KJgCWqBs7Jql_LotUMC:576025563) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/navigation/grid_maker/src/grid_maker_node.cpp#L181)):_

> ``` cpp
>         }
> 
>     map.header.frame_id = tf_prefix + "map";
> ```

Je me trompe peut-être mais il me semble que le createEmptyMap s'en charge et sur base de fame_id.

Et soit dit en passant, l'indentation semble mauvaise.

---

_[navigation/localisation/src/cartographie_node.cpp, line 29 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgDYylrbM99EZirqTy:-KJgDYylrbM99EZirqTz:1926497480) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/navigation/localisation/src/cartographie_node.cpp#L29)):_

> ``` cpp
>     static ros::NodeHandle nh;
>     std::string tf_prefix;
>     nh.param<std::string>("simuRobotNamespace", tf_prefix, "");;
> ```

Double point virgule :smile: 

---

_[navigation/localisation/src/cartographie_node.cpp, line 63 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgDjwzQXHGTfIkJjZ1:-KJgDjwzQXHGTfIkJjZ2:-441338857) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/navigation/localisation/src/cartographie_node.cpp#L63)):_

> ``` cpp
>         // Vérification de la zone
>         int zone = machineToArea(p);
>         //std::cout << "machine en zone " << zone << std::endl;
> ```

ROS_LOG, ROS_DEBUG, il faut qu'on se force à les manipuler.

---

_[navigation/localisation/src/cartographie_utils.cpp, line 151 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgE7wZDSPEuqwaUTf0:-KJgE7w_x3hOtaJdq9ai:-1459546160) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/navigation/localisation/src/cartographie_utils.cpp#L151)):_

> ``` cpp
>   if(dist(aMin,aMax) >= 0.5 &&
>      dist(bMin,bMax) >= 0.5 &&
>      (dist(aMin, bMin) <= 0.3 || dist(aMin, bMax) <= 0.3) &&
> ```

Ici, au dessus et en dessous, c'est des magic numbers.
S'il ne sont utilisés qu'ici et sont uniques, un commentaire suffira pour moi, sinon une constante voir une variable paramétrable stp.

---

_[navigation/localisation/src/landmarks_extraction_node.cpp, line 20 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgEWPVFfyTxdcwPNYU:-KJgEWPVFfyTxdcwPNYV:254106508) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/navigation/localisation/src/landmarks_extraction_node.cpp#L20)):_

> ``` cpp
>     ros::NodeHandle n;
>     std::string tf_prefix;
>     n.param<std::string>("simuRobotNamespace", tf_prefix, "");;
> ```

Double point virgule

---

_[navigation/localisation/src/LaserScan.cpp, line 109 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgF8yoajQb80TUnRJ4:-KJgF8yoajQb80TUnRJ5:111431200) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/navigation/localisation/src/LaserScan.cpp#L109)):_

> ``` cpp
>   m_angle_min = scan->angle_min;
>   m_angle_max = scan->angle_max;
>   m_angle_inc = scan->angle_increment;
> ```

Effectivement, c'est mieux :+1: 

---

_[navigation/localisation/src/visualisationOK.cpp, line 78 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgFK7QaJdfw27AOVra:-KJgFK7QaJdfw27AOVrb:254106508) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/navigation/localisation/src/visualisationOK.cpp#L78)):_

> ``` cpp
>   ros::NodeHandle n;
>   std::string tf_prefix;
>   n.param<std::string>("simuRobotNamespace", tf_prefix, "");;
> ```

Double point virgule

---

_[navigation/path_finder/src/PathPlanner.cpp, line 27 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgFXGVMFgp0f4wEEum:-KJgFXGVMFgp0f4wEEun:254106508) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/navigation/path_finder/src/PathPlanner.cpp#L27)):_

> ``` cpp
> {
>     std::string tf_prefix;
>     m_nh.param<std::string>("simuRobotNamespace", tf_prefix, "");;
> ```

Double point virgule

---

_[navigation/path_finder/src/PathPlanner.cpp, line 57 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgFZaO_j__kaJUTik6:-KJgFZaPA6Ks86x79F_e:254106508) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/navigation/path_finder/src/PathPlanner.cpp#L57)):_

> ``` cpp
>     m_nh.param<double>("navigation/pathFinder/weightSmooth", weightSmooth, 0.35);
>     std::string tf_prefix;
>     m_nh.param<std::string>("simuRobotNamespace", tf_prefix, "");;
> ```

Double point virgule

---

_[simulation/gazebo_to_ros/src/gazebo_to_ros_node.cpp, line 162 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgFlcOk1hXsGOb_bxC:-KJgFlcOk1hXsGOb_bxD:254106508) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/simulation/gazebo_to_ros/src/gazebo_to_ros_node.cpp#L162)):_

> ``` cpp
> 
>   g_landmarks.header.stamp = ros::Time::now();
>   nh.param<std::string>("simuRobotNamespace", tf_prefix, "");;
> ```

Double point virgule

---

_[traitement_image/ar_tag/launch/alvar_simu.launch, line 2 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJgFqNf90qQ0Nni5zz6:-KJgFqNf90qQ0Nni5zz7:-1993261362) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/442c2f426607ae8008cc94537ba8c621d5383d96/traitement_image/ar_tag/launch/alvar_simu.launch#L2)):_

> ``` XML
> <launch>
>   <group ns="robotino1">
> ```

Non, stp ne fais pas ça.
On utilise ce launchfile dans d'autres launchfiles globaux qui se chargent de mettre ce namespace ou celui d'un autre robot.

Tu peux rendre ce launchfile paramétrable à la limite pour qu'il puisse prendre un namespace quand on le lance individuellement, pourquoi pas, mais ne force pas le namespace à robotino1 stp.

Soit dit en passant, si tu met la variable d'environnement ROS_NAMESPACE (à confirmer) tous tes nœuds seront déplacés sous $ROS_NAMESPACE, pratique donc dans le cas ou tu le lances à part.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-:-KJgGYaQXDgn3qIfFYuC:-89637347)_

**Comment by tdanel** [comment]
Bon à reviewer

**Comment by vcoelen** [comment]
Reviewed 16 of 30 files at r3, 5 of 9 files at r4.
Review status: 33 of 43 files reviewed at latest revision, 24 unresolved discussions.

---

_[ci-travis/scripts/echoColor.sh, line 35 [r4]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJz_UolACE8fLIUWQlc:-KJz_UolACE8fLIUWQld:-384991941) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/800978d4be7d735005dc3b131f6bf42727d1f54b/ci-travis/scripts/echoColor.sh#L35)):_

> ``` Shell
>   "lb" | "lightblue" | "LIGHTBLUE")
>       START="\e[36m"
>       ;
> ```

!! Ne pas supprimer les doubles points virgules

---

_[manager/executeur_taches/include/LocaSubscriber.h, line 30 [r4]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJz_zZoWTpTNvvYZ-fd:-KJz_zZoWTpTNvvYZ-fe:1624146323) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/800978d4be7d735005dc3b131f6bf42727d1f54b/manager/executeur_taches/include/LocaSubscriber.h#L30)):_

> ``` objc
>       /* Méthodes */
>       void tesCallback(const deplacement_msg::LandmarksConstPtr &msg);
>       int getArea(float x, float y);
> ```

Utiliser les common

---

_[navigation/localisation/include/localisation/cartographie_utils.h, line 23 [r4]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJzbEp7LQkYnqOdVMOH:-KJzbEp7LQkYnqOdVMOI:-1701140688) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/800978d4be7d735005dc3b131f6bf42727d1f54b/navigation/localisation/include/localisation/cartographie_utils.h#L23)):_

> ``` objc
> #include <cmath>
> 
> int getArea(geometry_msgs::Pose2D m);
> ```

common

---

_[navigation/localisation/include/localisation/LaserScan.h, line 26 [r4]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJzdk7BOTVUckbbnwXI:-KJzdk7BOTVUckbbnwXJ:-834347312) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/800978d4be7d735005dc3b131f6bf42727d1f54b/navigation/localisation/include/localisation/LaserScan.h#L26)):_

> ``` objc
>   float getAngleMax() const;
>   float getAngleInc() const;
>   ros::Time getTime() const;
> ```

const ref ?

---

_[navigation/localisation/include/localisation/Segment.h, line 33 [r4]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJzeJvti85z_eZcrD8Q:-KJzeJvti85z_eZcrD8R:255882845) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/800978d4be7d735005dc3b131f6bf42727d1f54b/navigation/localisation/include/localisation/Segment.h#L33)):_

> ``` objc
> 
>   bool isAWall();
> */
> ```

A supprimer

---

_[navigation/localisation/src/cartographie_node.cpp, line 97 [r4]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJzfPGh1xW5ubnNRoQq:-KJzfPGiq0ln83sEbdda:2112726094) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/800978d4be7d735005dc3b131f6bf42727d1f54b/navigation/localisation/src/cartographie_node.cpp#L97)):_

> ``` cpp
>   {
>     // Changement de repère
>     geometry_msgs::Pose2D p = changeFrame(segments->landmarks[i], transform);
> ```

mettre changeFrame en common ?

---

_[navigation/localisation/src/cartographie_utils.cpp, line 67 [r4]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJzflQ7jrs1VeJcsJeZ:-KJzflQ7jrs1VeJcsJe_:-216776221) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/800978d4be7d735005dc3b131f6bf42727d1f54b/navigation/localisation/src/cartographie_utils.cpp#L67)):_

> ``` cpp
> bool isTheSame(Segment a, Segment b)
> {
>   if (dist(a.getMin(), b.getMin()) == 0 &&
> ```

comparer à un epsilon plutôt qu'à 0

---

_[navigation/localisation/src/cartographie_utils.cpp, line 244 [r4]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJzgQluwM_KXYNgDo_-:-KJzgQlv8rjNEq8tij40:-886690144) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/800978d4be7d735005dc3b131f6bf42727d1f54b/navigation/localisation/src/cartographie_utils.cpp#L244)):_

> ``` cpp
> void gatherTwoSegments(Segment &segment_1, Segment segment_2)
> {
>   if (dist(segment_2.getMax(), segment_1.getMin()) < 0.5)
> ```

Magic number ?

---

_[navigation/localisation/src/conversion_functions.cpp, line 109 [r4]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJzgcx_QkxOHqoOfcSw:-KJzgcx_QkxOHqoOfcSx:-542216668) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/800978d4be7d735005dc3b131f6bf42727d1f54b/navigation/localisation/src/conversion_functions.cpp#L109)):_

> ``` cpp
>     geometry_msgs::Pose2D pose2d;
>     pose2d.x = point.x;
>     pose2d.y = point.y;
> ```

tu peux factoriser en appelant la fonction du dessus "pointToPose2D(const geometry_msgs::Point &point)"

---

_[navigation/localisation/src/Line.cpp, line 40 [r4]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJzhhsNYJkrI6hU_F5Q:-KJzhhsNYJkrI6hU_F5R:1971298312) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/800978d4be7d735005dc3b131f6bf42727d1f54b/navigation/localisation/src/Line.cpp#L40)):_

> ``` cpp
>   p.x = (b.x + a.x)/2;
>   p.y = (b.y + a.y)/2;
>   // to be true, this is the slope of the line, not its angle
> ```

inconsistant avec getAngle et getSlope

---

_[navigation/localisation/src/visualisationOK.cpp, line 85 [r4]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KJziLbsER1DpFNk0ZQy:-KJziLbsER1DpFNk0ZQz:-1936331140) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/800978d4be7d735005dc3b131f6bf42727d1f54b/navigation/localisation/src/visualisationOK.cpp#L85)):_

> ``` cpp
> 
>   ros::Subscriber sub_machines    = n.subscribe("objectDetection/landmarks", 1000, landmarksCallback);
>   ros::Subscriber sub_segments    = n.subscribe("objectDetection/segments_global", 100000, segmentsCallback);
> ```

100000 ????

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64)_

**Comment by vcoelen** [comment]
Reviewed 1 of 30 files at r3, 18 of 19 files at r5.
Review status: 48 of 49 files reviewed at latest revision, 25 unresolved discussions.

---

_[navigation/localisation/src/conversion_functions.cpp, line 11 [r5]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-KK-68CQSdV8MBSJGFIi:-KK-68CQSdV8MBSJGFIj:221143282) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/6f8c9f06b2c0f0a330d015ec18712caeb578f5fd/navigation/localisation/src/conversion_functions.cpp#L11)):_

> ``` cpp
> using namespace Eigen;
> 
> geometry_msgs::Pose2D changeFrame(const geometry_msgs::Pose2D &p, const tf::StampedTransform &transform)
> ```

à mettre dans geometry_utils

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64)_

**Comment by vcoelen** [comment]
Reviewed 16 of 16 files at r6.
Review status: all files reviewed at latest revision, 25 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64)_

**Comment by vcoelen** [comment]
:lgtm:

<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> Bon à reviewer
> </details>

---

Review status: all files reviewed at latest revision, 25 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-:-KK-UhQD3GdYr2g3eL8J:1417088721)_

**Comment by vcoelen** [comment]
Reviewed 3 of 4 files at r7.
Review status: 57 of 58 files reviewed at latest revision, 25 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64)_

**Comment by vcoelen** [comment]
:lgtm:

<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> :lgtm:
> </details>

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 25 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/64#-:-KK-bRzm2-8oU248nAwZ:1417088721)_

**Pull request merged**
