### PR TITLE
Ajout RobotInfo dans le noeud refBoxComm

### PR DESCRIPTION
**Pull request by ValentinVERGEZ**
J'ouvre la PR pour relecture d'abord, puis pour intégration.
Dev à tester p-e ?

@vcoelen je te laisses nous dire ce qu'il en est.

---

This change is [Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/123)

### CODE REVIEW

**Comment by ValentinVERGEZ** [comment]
J'ai bien des questions, mais au final ça paraît bon pour moi. L'essentiel est là :lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[communication/refbox_comm/src/refBoxComm.cpp, line 442 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-KMsekjqCvvRROkmyPP7:-KMsekjqCvvRROkmyPP8:1516083359) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/ff931186c1d70b4871ec4dd595c62da46d182414/communication/refbox_comm/src/refBoxComm.cpp#L442)):_

> ``` cpp
>         boost::posix_time::time_duration const last_seen_ago_td = now - last_seen;
>         float last_seen_ago = last_seen_ago_td.total_milliseconds() / 1000.f;
> */
> ```

Tu comptes garder ou tu ne gardes pas ?

---

_[communication/refbox_comm/src/refBoxComm.cpp, line 444 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-KMsesNd2P2F6nhMgPIG:-KMsesNeBdItvnFEa_qO:1022129469) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/ff931186c1d70b4871ec4dd595c62da46d182414/communication/refbox_comm/src/refBoxComm.cpp#L444)):_

> ``` cpp
> */
>         float last_seen_ago = 0;
>         printf("  %u %s/%s @ %s: state %s, last seen %f sec ago  Maint cyc: %u  rem: %f\n",
> ```

printf ?

---

_[communication/refbox_comm/src/refBoxUtils.cpp, line 184 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-KMsiXOMIytiO6-12KbS:-KMsiXONE6FpIi13GFot:-673098869) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/ff931186c1d70b4871ec4dd595c62da46d182414/communication/refbox_comm/src/refBoxUtils.cpp#L184)):_

> ``` cpp
> 
>         //TODO: convetir last_seen
>         //rosRobot.last_seen = llsfRobot.last_seen();
> ```

Sous quel format tu voudras représenter le temps ? (comment on gère la synchro ?)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-:-KMsj0UTqigXj8YFc8Yz:-111341848)_

**Comment by tdanel** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

_[communication/refbox_comm/src/refBoxComm.cpp, line 122 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-KMso_xYnSVXDET3CMje:-KMso_xYnSVXDET3CMjf:680701893) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/ff931186c1d70b4871ec4dd595c62da46d182414/communication/refbox_comm/src/refBoxComm.cpp#L122)):_

> ``` cpp
> }
> 
> bool RefBoxComm::ReportMachineSrv(comm_msg::ReportMachine::Request  &req,
> ```

On pourrait ajouter maintenant le report différencié ?

---

_[communication/refbox_comm/src/refBoxComm.cpp, line 343 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-KMsonmEOl6Lx0hlIIj3:-KMsonmEOl6Lx0hlIIj4:988554645) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/ff931186c1d70b4871ec4dd595c62da46d182414/communication/refbox_comm/src/refBoxComm.cpp#L343)):_

> ``` cpp
>   ExplorationInfo &ei = dynamic_cast<ExplorationInfo&>(m);
> 
>   /*
> ```

Pas mal de clean à faire ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123)_

**Comment by ValentinVERGEZ** [comment]
@tdanel Est-ce que le clean est nécessaire pour l'intégration de la PR à tes yeux ?
En tous cas pas pour moi.

**Comment by vcoelen** [comment]
Ne pas merger!!!
Si je me souviens bien, le dev n'est pas terminé, je vais y regarder. En tout cas, il est certain que ça n'a pas été testé.
Je verrais pour tenir compte des remarques au passage.

**Comment by tdanel** [comment]
Nan le clean se fera dans la branche work/vincent/cleanup.postRobocup2016 mais juste pour pas oublier

**Comment by vcoelen** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

_[communication/refbox_comm/src/refBoxComm.cpp, line 122 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-KMso_xYnSVXDET3CMje:-KMsxsxOS0690SOGkF1h:-1962490229) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/ff931186c1d70b4871ec4dd595c62da46d182414/communication/refbox_comm/src/refBoxComm.cpp#L122)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> On pourrait ajouter maintenant le report différencié ?
> </details>
> On peut, mais pas dans cette branche :)

---

_[communication/refbox_comm/src/refBoxComm.cpp, line 343 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-KMsonmEOl6Lx0hlIIj3:-KMsy926d5BjOTXIocWE:2026589841) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/ff931186c1d70b4871ec4dd595c62da46d182414/communication/refbox_comm/src/refBoxComm.cpp#L343)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> Pas mal de clean à faire ?
> </details>
> Oui :)

---

_[communication/refbox_comm/src/refBoxComm.cpp, line 442 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-KMsekjqCvvRROkmyPP7:-KMsyAALWC5zyPy9Ex5h:2099222208) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/ff931186c1d70b4871ec4dd595c62da46d182414/communication/refbox_comm/src/refBoxComm.cpp#L442)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> Tu comptes garder ou tu ne gardes pas ?
> </details>
> Ça dégagera, à priori

---

_[communication/refbox_comm/src/refBoxComm.cpp, line 444 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-KMsesNd2P2F6nhMgPIG:-KMsx0htI67A9xBTUokF:-2139105978) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/ff931186c1d70b4871ec4dd595c62da46d182414/communication/refbox_comm/src/refBoxComm.cpp#L444)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> printf ?
> </details>
> Oui, il y a des std::cout aussi. :) Un peu d'indulgence c'est du code qui remonte à très longtemps. :) C'est même très probablement un bout de code provenant de l'exemple de la refbox

---

_[communication/refbox_comm/src/refBoxUtils.cpp, line 184 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-KMsiXOMIytiO6-12KbS:-KMsxVKP_6S9vJqje4q9:-1629236577) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/ff931186c1d70b4871ec4dd595c62da46d182414/communication/refbox_comm/src/refBoxUtils.cpp#L184)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> Sous quel format tu voudras représenter le temps ? (comment on gère la synchro ?)
> </details>
> C'est un ros::time dans le message, je n'ai pas encore fait la conversion.
> Quelle synchro?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123)_

**Comment by vcoelen** [comment]
@ValentinVERGEZ , pourquoi tu veux merger cette branche dans work/vincent/cleanup.postRobocup2016?

**Comment by ValentinVERGEZ** [comment]
Oups pardon. Non j'ai ouvert la PR sur ça pour y voir plus clair sur les véritables ajouts.

**Comment by ValentinVERGEZ** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

_[communication/refbox_comm/src/refBoxUtils.cpp, line 184 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-KMsiXOMIytiO6-12KbS:-KMt-7EUpLAIfdpnuMAV:-1172593059) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/ff931186c1d70b4871ec4dd595c62da46d182414/communication/refbox_comm/src/refBoxUtils.cpp#L184)):_
<details><summary>

<i>Previously, vcoelen wrote…</i></summary>



> C'est un ros::time dans le message, je n'ai pas encore fait la conversion.
> Quelle synchro?
> </details>
> En match, si le robot est desynchro avec la refbox (en terme de temps), ça donnera n'importe quoi.

En simu, c'est une autre forme de problème, ros::Time se calera sur le topic publié par gazebo /clock. Il faudrait que la refbox aussi soit synchro dessus.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123)_

**Comment by vcoelen** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

_[communication/refbox_comm/src/refBoxUtils.cpp, line 184 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-KMsiXOMIytiO6-12KbS:-KMt0VaaAPafSSWDWAb3:-1412928023) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/ff931186c1d70b4871ec4dd595c62da46d182414/communication/refbox_comm/src/refBoxUtils.cpp#L184)):_
<details><summary>

<i>Previously, ValentinVERGEZ (Valentin VERGEZ) wrote…</i></summary>



> En match, si le robot est desynchro avec la refbox (en terme de temps), ça donnera n'importe quoi.
> 
> En simu, c'est une autre forme de problème, ros::Time se calera sur le topic publié par gazebo /clock. Il faudrait que la refbox aussi soit synchro dessus.
> </details>
> Possible, mais dans cette partie du code je ne fais que renvoyer ce que donne la refBox. C'est à dire le temps UTC du dernier signal beacon qu'elle a reçue d'un robot donné. Je ne fait aucun calcul.
> Pour la simulation, pareil, le noeud refbox_comm ne fait que transmettre de l'information.
> Il y a une config au niveau de la refBox pour la synchroniser avec le simulateur.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123)_

**Comment by vcoelen** [comment]
Sauf problème à corriger, je ne pense pas aller plus loin sur cette branche. Le retour de maintenance fera parti des choses à intégrer au nouvel exécuteur de tâche.

**Comment by tdanel** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/123#-:-KN20-5VxDVVTmhmztnL:1417088721)_

**Comment by tdanel** [comment]
On peut merge du coup ?

**Comment by ValentinVERGEZ** [comment]
Oui, mais p-e sur une autre branche (à la main ou via nouvelle PR).
C'est quoi notre branche de référence pour le cleanup de l'été (avant intégration sur devel) ?

**Comment by vcoelen** [comment]
Normalement, c'est la branche "work/FinaleRobocup2016".
Sinon, il n'y a vraiment que du dev sur la refBox dans cette branche et ça n'a pas été utilisé pendant la robocup, donc ça peut aussi attendre la fin du cleanuo de l'été pour être intégré par la suite sur devel.

**Comment by ValentinVERGEZ** [comment]
C'est mergé dans base/cleanup.AfterRobocup2016

**Pull request closed without merging**
