### PR TITLE
Work/vincent/navigation/path tracker/new path tracker and avoidance

### PR DESCRIPTION
**Pull request by vcoelen**
Nouveau Pathtracker, pas d'évitement d'obstacle

---

This change is [Reviewable](https://reviewable.io/reviews/pyroteam/robocup-pkg/82)

### CODE REVIEW

**Comment by tdanel** [comment]
Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_[navigation/navigation_manager/src/moveToPose.cpp, line 185 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-KLDDQfY-7NVaHfAg7nb:-KLDDQfY-7NVaHfAg7nc:-2085619998) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/baa2d08e01d09248229433d85db31ebac8ea2308/navigation/navigation_manager/src/moveToPose.cpp#L185)):_

> ``` cpp
> void MoveToPose::PoseCallback(const nav_msgs::Odometry &odom)
> {
>     geometry_msgs::PoseStamped poseIn;
> ```

common_utils

---

_[navigation/path_tracker/include/path_tracker/BasicFollower.h, line 28 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-KLDEBD4wgg3i-ODPBRa:-KLDEBD4wgg3i-ODPBRb:-939469119) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/baa2d08e01d09248229433d85db31ebac8ea2308/navigation/path_tracker/include/path_tracker/BasicFollower.h#L28)):_

> ``` objc
>         std::shared_ptr<common_utils::Controller> controllerOri):
>         PathFollower(controllerVel, controllerOri),
>         m_speedLimiter(-0.20, 0.20, 1/10.0)//TODO à parametrer
> ```

Magic number

---

_[navigation/path_tracker/include/path_tracker/PathTracking.h, line 72 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-KLDHH2gVH994nosVXjC:-KLDHH2h0UEexrU7ETNl:1726659578) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/baa2d08e01d09248229433d85db31ebac8ea2308/navigation/path_tracker/include/path_tracker/PathTracking.h#L72)):_

> ``` objc
>     }
> private:
>     int m_count;
> ```

ne sert plus apparemment

---

_[navigation/path_tracker/src/BasicFollower.cpp, line 24 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-KLDIir6Usr-8lTHKG-o:-KLDIir6Usr-8lTHKG-p:677143941) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/baa2d08e01d09248229433d85db31ebac8ea2308/navigation/path_tracker/src/BasicFollower.cpp#L24)):_

> ``` cpp
> //vitesse min robotino fixe
> //TODO: à parametrer
> const float VminStatic = 0.05;
> ```

VU !

---

_[navigation/path_tracker/src/BasicFollower.cpp, line 132 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-KLDL-9_ZgqeG68L1tvJ:-KLDL-9_ZgqeG68L1tvK:-962223221) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/baa2d08e01d09248229433d85db31ebac8ea2308/navigation/path_tracker/src/BasicFollower.cpp#L132)):_

> ``` cpp
>             twist.linear.x = 0;
>             twist.linear.y = 0;
>             //orienation finale
> ```

Orientation

---

_[navigation/path_tracker/src/BasicFollower.cpp, line 142 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-KLDL36QT-OYUVoLPSh-:-KLDL36QT-OYUVoLPSh0:1384738699) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/baa2d08e01d09248229433d85db31ebac8ea2308/navigation/path_tracker/src/BasicFollower.cpp#L142)):_

> ``` cpp
>             {
>                 twist.angular.z = m_controllerOri->update(errOrie);
>                 //twist.angular.z = saturation(cmdVel_msg.angular.z, -1.0, 1.0);
> ```

to delete

---

_[navigation/path_tracker/src/PathFollower.cpp, line 22 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-KLDLzyteRwDrLHagivj:-KLDLzyteRwDrLHagivk:-939469119) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/baa2d08e01d09248229433d85db31ebac8ea2308/navigation/path_tracker/src/PathFollower.cpp#L22)):_

> ``` cpp
>         m_controllerOri(controllerOri),
>         m_status(PathFollowerStatus_t::TRAJ_END),
>         m_Vmax(0.3)
> ```

Magic number

---

_[navigation/path_tracker/src/PathTracking.cpp, line 105 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-KLDOcAjU7mv_5YeN_Ng:-KLDOcAjU7mv_5YeN_Nh:-223081579) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/baa2d08e01d09248229433d85db31ebac8ea2308/navigation/path_tracker/src/PathTracking.cpp#L105)):_

> ``` cpp
> 
>         //fin d'action, retourner le résultat
>         if (isTrajEnd)
> ```

utilité relative

---

_[navigation/path_tracker/src/SwitchModeBehavior.cpp, line 25 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-KLDP64NCyrb6rheszgh:-KLDP64NCyrb6rheszgi:-610751853) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/baa2d08e01d09248229433d85db31ebac8ea2308/navigation/path_tracker/src/SwitchModeBehavior.cpp#L25)):_

> ``` cpp
> }
> 
> geometry_msgs::Twist SwitchModeBehavior::generateNewSetPoint()
> ```

Setpoint

---

_[navigation/path_tracker/src/SwitchModeBehavior.cpp, line 82 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-KLDPGZ8o0tvplcQ4bxG:-KLDPGZ8o0tvplcQ4bxH:-472154224) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/baa2d08e01d09248229433d85db31ebac8ea2308/navigation/path_tracker/src/SwitchModeBehavior.cpp#L82)):_

> ``` cpp
>         else
>         {
>             ROS_ERROR("In Avoid Obstacle mode, but no adoidObstacle assigned!");
> ```

avoid

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82)_

**Comment by ValentinVERGEZ** [comment]
Globalement d'accord avec Thomas sur les remarques.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-:-KLDXj1SS5_yLh0LYuy2:946515470)_

**Comment by vcoelen** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_[navigation/path_tracker/src/PathFollower.cpp, line 22 [r1]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-KLDLzyteRwDrLHagivj:-KLDUdEI2lp_ZgzXZvQT:-322888764) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/baa2d08e01d09248229433d85db31ebac8ea2308/navigation/path_tracker/src/PathFollower.cpp#L22)):_
<details><summary>

<i>Previously, tdanel (Thomas DANEL) wrote…</i></summary>



> Magic number
> </details>
> C'est une valeur d'initialisation :p

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82)_

**Comment by tdanel** [comment]
:lgtm: 

---

Reviewed 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_[navigation/navigation_manager/include/navigation_manager/moveToPose.h, line 70 [r2]](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-KLFiCo7Q7fZJjZqJJnU:-KLFiCo7Q7fZJjZqJJnV:-1654060869) ([raw file](https://github.com/pyroteam/robocup-pkg/blob/e54536e4c6a3c5a0183e216523350e802ee49f83/navigation/navigation_manager/include/navigation_manager/moveToPose.h#L70)):_

> ``` objc
>                                      m_robotPose("map")
>       {
>           m_sharpSensorSub = m_nh.subscribe("hardware/distance_sensors", 1000, &MoveToPose::DistSensorCallback, this);
> ```

Achtung

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pyroteam/robocup-pkg/82#-:-KLFjekkHsk27jaMv-8_:980077423)_

**Pull request merged**
